import React from 'react';

export default function EvidenceDrawer({ isOpen, onClose, schoolName, evidence = [], categories = [] }) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 overflow-hidden">
      <div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={onClose} />
      
      <div className="absolute inset-y-0 right-0 max-w-full flex">
        <div className="w-screen max-w-md transform transition ease-in-out duration-500">
          <div className="h-full flex flex-col bg-slate-900 shadow-2xl border-l border-slate-800">
            {/* Header */}
            <div className="px-6 py-6 bg-slate-800/50 border-b border-slate-800">
              <div className="flex items-start justify-between">
                <h2 className="text-xl font-bold text-white">Prediction Evidence</h2>
                <button
                  onClick={onClose}
                  className="rounded-md text-slate-400 hover:text-white focus:outline-none"
                >
                  <span className="sr-only">Close panel</span>
                  <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
              <p className="mt-1 text-sm text-slate-400">
                Data insights for <span className="text-blue-400 font-semibold">{schoolName}</span>
              </p>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto p-6 space-y-6">
              {/* Categories */}
              <div>
                <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-3">At-Risk Categories</h3>
                <div className="flex flex-wrap gap-2">
                  {categories.map(cat => (
                    <span key={cat} className="px-2.5 py-1 rounded-full bg-slate-800 border border-slate-700 text-xs font-medium text-slate-300 capitalize">
                      {cat}
                    </span>
                  ))}
                </div>
              </div>

              {/* Evidence List */}
              <div>
                <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-3">Supporting Indicators</h3>
                {evidence.length > 0 ? (
                  <ul className="space-y-4">
                    {evidence.map((item, idx) => (
                      <li key={idx} className="flex gap-3 items-start p-3 rounded-lg bg-slate-800/40 border border-slate-800">
                        <div className="mt-1 h-2 w-2 rounded-full bg-blue-500 shrink-0" />
                        <span className="text-sm text-slate-300 leading-relaxed">{item}</span>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <div className="text-center py-8 border-2 border-dashed border-slate-800 rounded-xl">
                    <p className="text-sm text-slate-500">No specific evidence items cited.</p>
                  </div>
                )}
              </div>

              {/* Methodology note */}
              <div className="p-4 rounded-xl bg-blue-500/5 border border-blue-500/10">
                <div className="flex gap-3">
                  <svg className="h-5 w-5 text-blue-400 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  <p className="text-xs text-blue-300/80 leading-relaxed">
                    These triggers are automatically generated by the prediction engine by analyzing 4-week condition trends and regional weather modifiers.
                  </p>
                </div>
              </div>
            </div>

            {/* Footer */}
            <div className="px-6 py-6 bg-slate-800/30 border-t border-slate-800">
              <button
                onClick={onClose}
                className="w-full py-2.5 px-4 rounded-lg bg-slate-800 hover:bg-slate-700 text-white text-sm font-medium transition-colors border border-slate-700"
              >
                Close Insights
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
