import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  en: {
    'wo.title': 'Infrastructure Directives',
    'wo.subtitle.contractor': 'Allocated Tasks Requiring Operational Resolution',
    'wo.subtitle.deo': 'Operational Oversight of District-wide Maintenance Assignments',
    'wo.auth_btn': 'Authorize Directive',
    'wo.total': 'Total Directives',
    'wo.active': 'Active Orders',
    'wo.completed': 'Completed',
    'wo.sla': 'SLA Breaches',
    'wo.alert.title': 'SLA Compliance Alert',
    'wo.alert.desc': 'Directives exceeding authorized timelines',
    'wo.tab.all': 'ALL REGISTRY',
    'wo.loading': 'Syncing Registry...',
    'wo.empty': 'No matching work orders found in the registry.',
    'wo.th.type': 'Type',
    'wo.th.location': 'Asset Location',
    'wo.th.personnel': 'Personnel',
    'wo.th.deadline': 'Deadline',
    'wo.th.offset': 'Offset',
    'wo.th.status': 'Status',
    'wo.th.actions': 'Actions',
    'wo.ref': 'REF:',
    'wo.unknown_node': 'Unknown Node',
    'wo.unassigned': 'Unassigned',
    'wo.na': 'NA',
    'wo.breach_badge': 'SLA Breach',
    'wo.days': 'DAYS',
    'wo.btn.assign': 'Assign',
    'wo.btn.complete': 'Authorize Closure',
    'status.pending': 'Pending',
    'status.assigned': 'Assigned',
    'status.in_progress': 'In Progress',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    'deo.title': 'Administrative Oversight Center',
    'deo.subtitle': 'District Infrastructure Health & Predictive Maintenance Management',
    'deo.all_work_orders': 'All Work Orders',
    'deo.assessed_schools': 'Assessed Schools',
    'deo.critical_risk': 'Critical Risk',
    'deo.high_priority': 'High Priority',
    'deo.trending': 'Trending',
    'deo.avg_survival': 'Avg Survival',
    'deo.days': 'Days',
    'deo.risk_queue_title': 'Risk Management Queue',
    'deo.risk_queue_subtitle': 'Real-time predictive analysis of infrastructure nodes',
    'deo.risk_queue_tab': 'Risk Queue',
    'deo.gps_mismatches_tab': 'GPS Mismatches',
    'deo.filter_placeholder': 'Filter District...',
    'deo.loading_scans': 'Loading Risk Scans...',
    'deo.no_critical_nodes': 'No critical risk nodes identified in current registry scan.',
    'deo.score': 'Score',
    'deo.failure_horizon': 'Failure Horizon',
    'deo.student_impact': 'Student Impact',
    'deo.pts': 'Pts',
    'deo.resolve': 'Resolve',
    'deo.no_mismatches': 'NO LOCATION MISMATCHES DETECTED',
    'deo.th.protocol': 'Protocol',
    'deo.th.contractor': 'Contractor / Site',
    'deo.th.coordinates': 'Coordinates',
    'deo.th.alert': 'Alert',
    'deo.th.variance': 'Variance',
    'deo.verify_proof': 'Verify Proof',
    'deo.unknown_school': 'Unknown School',
    'deo.verified_by': 'Verified By',
    'deo.staff': 'Staff',
    'deo.submitted': 'SUBMITTED',
    'deo.registry': 'REGISTRY',
    'deo.location_variance': 'Location Variance',
    'deo.breach_detected': 'Breach Detected',
    'deo.outside_perimeter': 'Outside Security Perimeter',
    'deo.last_sync': 'Last Synchronization',
    'deo.security_registry_operational': 'Security Registry Operational',
    'sv.analyzing': 'Analysing Profile...',
    'sv.access_restricted': 'Access Restricted',
    'sv.admin_credentials_req': 'Administrative credentials required to view this profile.',
    'sv.unspecified_region': 'Unspecified Region',
    'sv.age': 'Age',
    'sv.registry': 'Registry',
    'sv.generic_node': 'Generic Node',
    'sv.admin_oversight': 'Administrative Oversight Center',
    'sv.submit_audit': 'Submit Audit',
    'sv.resource_registry': 'Resource Registry',
    'sv.infra_health': 'Infrastructure Health',
    'sv.global_condition': 'Global condition index',
    'sv.pending_audits': 'Pending Audits',
    'sv.due_this_month': 'due this month',
    'sv.critical_risks': 'Critical Risks',
    'sv.high_risk_vectors': 'High risk vectors',
    'sv.audit_history': 'Audit History',
    'sv.registry_volume': 'Registry Volume',
    'sv.risk_spectrum': 'Risk Spectrum',
    'sv.domain_specific': 'Domain-specific assessment',
    'sv.infra_survival': 'Infrastructure Survival Analysis',
    'sv.predictive_engine': 'Predictive Analytics Engine',
    'sv.failure_horizon': 'Failure Horizon',
    'sv.trend_vector': 'Trend & Vector',
    'sv.critical_worst': 'Critical',
    'sv.none': 'None',
    'sv.insufficient_data': 'Insufficient audit data for predictive survival analysis.',
    'gs.cap_1_title': 'Structural Forecaster',
    'gs.cap_1_desc': 'AI-driven detection of concrete degradation and slab stress.',
    'gs.cap_2_title': 'Impact Priority',
    'gs.cap_2_desc': 'Automatic ranking based on student usage and facility type.',
    'gs.cap_3_title': '60-Day Horizon',
    'gs.cap_3_desc': 'Failure window predictions for plumbing and electrical grids.',
    'gs.cap_4_title': '2-Min Staff Audit',
    'gs.cap_4_desc': 'Structured weekly health reports with zero free-text friction.',
    'gs.cap_5_title': 'GPS Verification',
    'gs.cap_5_desc': 'Contractor resolution audits with geo-tagged documentation.',
    'gs.cap_6_title': 'SLA Tracking',
    'gs.cap_6_desc': 'Real-time monitoring of complaint resolution timelines.',
    'gs.cap_7_title': 'DEO Dashboard',
    'gs.cap_7_desc': 'Centralized district-wide asset health visualization.',
    'gs.cap_8_title': 'Predictive Risk',
    'gs.cap_8_desc': 'Identify high-risk zones using building age and weather data.',
    'gs.cap_8_title': 'Predictive Risk',
    'gs.cap_8_desc': 'Identify high-risk zones using building age and weather data.',
    'gs.live_intelligence': 'Live Intelligence',
    'gs.engine': 'Engine',
    'gs.capabilities': 'Capabilities.',
    'ht.loading_chart': 'Loading Chart...',
    'ht.title': 'Infrastructure Health Timeline',
    'ht.subtitle': 'Historical condition analysis across domains',
    'ht.plumbing': 'Plumbing',
    'ht.electrical': 'Electrical',
    'ht.structural': 'Structural',
    'ht.footer_text': 'Higher values indicate optimal infrastructure integrity (0-100 index)'
  },
  hi: {
    'wo.title': 'बुनियादी ढांचा निर्देश',
    'wo.subtitle.contractor': 'कार्यात्मक समाधान की आवश्यकता वाले आवंटित कार्य',
    'wo.subtitle.deo': 'जिले भर के रखरखाव कार्यों की परिचालन निगरानी',
    'wo.auth_btn': 'नया निर्देश बनाएं',
    'wo.total': 'कुल निर्देश',
    'wo.active': 'सक्रिय आदेश',
    'wo.completed': 'पूर्ण',
    'wo.sla': 'SLA उल्लंघन',
    'wo.alert.title': 'SLA अनुपालन चेतावनी',
    'wo.alert.desc': 'अधिकृत समय सीमा पार करने वाले निर्देश',
    'wo.tab.all': 'सभी',
    'wo.loading': 'डेटा सिंक हो रहा है...',
    'wo.empty': 'कोई मेल खाने वाले कार्य आदेश नहीं मिले।',
    'wo.th.type': 'प्रकार',
    'wo.th.location': 'स्थान',
    'wo.th.personnel': 'कर्मचारी',
    'wo.th.deadline': 'समय सीमा',
    'wo.th.offset': 'विलंब',
    'wo.th.status': 'स्थिति',
    'wo.th.actions': 'कार्रवाइयां',
    'wo.ref': 'संदर्भ:',
    'wo.unknown_node': 'अज्ञात स्थान',
    'wo.unassigned': 'कोई नहीं',
    'wo.na': 'लागू नहीं',
    'wo.breach_badge': 'SLA उल्लंघन',
    'wo.days': 'दिन',
    'wo.btn.assign': 'सौंपें',
    'wo.btn.complete': 'पूर्ण करें',
    'status.pending': 'लंबित',
    'status.assigned': 'सौंपा गया',
    'status.in_progress': 'प्रगति पर',
    'status.completed': 'पूर्ण',
    'status.cancelled': 'रद्द',
    'deo.title': 'प्रशासनिक निरीक्षण केंद्र',
    'deo.subtitle': 'जिला बुनियादी ढांचा स्वास्थ्य और भविष्य कहनेवाला रखरखाव प्रबंधन',
    'deo.all_work_orders': 'सभी कार्य आदेश',
    'deo.assessed_schools': 'आंकलित स्कूल',
    'deo.critical_risk': 'गंभीर जोखिम',
    'deo.high_priority': 'उच्च प्राथमिकता',
    'deo.trending': 'रुझान',
    'deo.avg_survival': 'औसत जीवन',
    'deo.days': 'दिन',
    'deo.risk_queue_title': 'जोखिम प्रबंधन कतार',
    'deo.risk_queue_subtitle': 'बुनियादी ढांचे के नोड्स का वास्तविक समय पूर्वानुमान विश्लेषण',
    'deo.risk_queue_tab': 'जोखिम कतार',
    'deo.gps_mismatches_tab': 'जीपीएस विसंगतियां',
    'deo.filter_placeholder': 'जिला खोजें...',
    'deo.loading_scans': 'जोखिम स्कैन लोड हो रहा है...',
    'deo.no_critical_nodes': 'वर्तमान रजिस्ट्री स्कैन में कोई गंभीर जोखिम नोड नहीं मिला।',
    'deo.score': 'स्कोर',
    'deo.failure_horizon': 'विफलता सीमा',
    'deo.student_impact': 'छात्र प्रभाव',
    'deo.pts': 'अंक',
    'deo.resolve': 'समाधान करें',
    'deo.no_mismatches': 'कोई स्थान विसंगति नहीं मिली',
    'deo.th.protocol': 'प्रोटोकॉल',
    'deo.th.contractor': 'ठेकेदार / साइट',
    'deo.th.coordinates': 'निर्देशांक',
    'deo.th.alert': 'चेतावनी',
    'deo.th.variance': 'भिन्नता',
    'deo.verify_proof': 'प्रमाण सत्यापित करें',
    'deo.unknown_school': 'अज्ञात स्कूल',
    'deo.verified_by': 'द्वारा सत्यापित',
    'deo.staff': 'स्टाफ',
    'deo.submitted': 'प्रस्तुत',
    'deo.registry': 'रजिस्ट्री',
    'deo.location_variance': 'स्थान भिन्नता',
    'deo.breach_detected': 'उल्लंघन का पता चला',
    'deo.outside_perimeter': 'सुरक्षा परिधि के बाहर',
    'deo.last_sync': 'अंतिम सिंक्रनाइज़ेशन',
    'deo.security_registry_operational': 'सुरक्षा रजिस्ट्री चालू है',
    'sv.analyzing': 'प्रोफ़ाइल का विश्लेषण कर रहा है...',
    'sv.access_restricted': 'पहुंच प्रतिबंधित',
    'sv.admin_credentials_req': 'इस प्रोफ़ाइल को देखने के लिए प्रशासनिक क्रेडेंशियल आवश्यक हैं।',
    'sv.unspecified_region': 'अनिर्दिष्ट क्षेत्र',
    'sv.age': 'आयु',
    'sv.registry': 'रजिस्ट्री',
    'sv.generic_node': 'सामान्य नोड',
    'sv.admin_oversight': 'प्रशासनिक निरीक्षण केंद्र',
    'sv.submit_audit': 'ऑडिट जमा करें',
    'sv.resource_registry': 'संसाधन रजिस्ट्री',
    'sv.infra_health': 'बुनियादी ढांचा स्वास्थ्य',
    'sv.global_condition': 'वैश्विक स्थिति सूचकांक',
    'sv.pending_audits': 'लंबित ऑडिट',
    'sv.due_this_month': 'इस महीने देय',
    'sv.critical_risks': 'गंभीर जोखिम',
    'sv.high_risk_vectors': 'उच्च जोखिम वैक्टर',
    'sv.audit_history': 'ऑडिट इतिहास',
    'sv.registry_volume': 'रजिस्ट्री वॉल्यूम',
    'sv.risk_spectrum': 'जोखिम स्पेक्ट्रम',
    'sv.domain_specific': 'डोमेन-विशिष्ट मूल्यांकन',
    'sv.infra_survival': 'बुनियादी ढांचा जीवन विश्लेषण',
    'sv.predictive_engine': 'भविष्य कहनेवाला विश्लेषिकी इंजन',
    'sv.failure_horizon': 'विफलता सीमा',
    'sv.trend_vector': 'रुझान और वेक्टर',
    'sv.critical_worst': 'गंभीर',
    'sv.none': 'कोई नहीं',
    'sv.insufficient_data': 'भविष्य कहनेवाला जीवन विश्लेषण के लिए अपर्याप्त ऑडिट डेटा।',
    'gs.cap_1_title': 'संरचनात्मक पूर्वानुमानकर्ता',
    'gs.cap_1_desc': 'कंक्रीट क्षरण और स्लैब तनाव का एआई-संचालित पता लगाना।',
    'gs.cap_2_title': 'प्रभाव प्राथमिकता',
    'gs.cap_2_desc': 'छात्र उपयोग और सुविधा प्रकार के आधार पर स्वचालित रैंकिंग।',
    'gs.cap_3_title': '60-दिन की सीमा',
    'gs.cap_3_desc': 'पाइपलाइन और विद्युत ग्रिड के लिए विफलता खिड़की की भविष्यवाणी।',
    'gs.cap_4_title': '2-मिनट स्टाफ ऑडिट',
    'gs.cap_4_desc': 'शून्य मुक्त-पाठ घर्षण के साथ संरचित साप्ताहिक स्वास्थ्य रिपोर्ट।',
    'gs.cap_5_title': 'जीपीएस सत्यापन',
    'gs.cap_5_desc': 'जियो-टैग किए गए दस्तावेज़ों के साथ ठेकेदार समाधान ऑडिट।',
    'gs.cap_6_title': 'SLA ट्रैकिंग',
    'gs.cap_6_desc': 'शिकायत समाधान समयसीमा की वास्तविक समय की निगरानी।',
    'gs.cap_7_title': 'DEO डैशबोर्ड',
    'gs.cap_7_desc': 'केंद्रीकृत जिला-व्यापी संपत्ति स्वास्थ्य दृश्य।',
    'gs.cap_8_title': 'भविष्य कहनेवाला जोखिम',
    'gs.cap_8_desc': 'इमारत की उम्र और मौसम के डेटा का उपयोग करके उच्च जोखिम वाले क्षेत्रों की पहचान करें।',
    'gs.cap_8_title': 'भविष्य कहनेवाला जोखिम',
    'gs.cap_8_desc': 'इमारत की उम्र और मौसम के डेटा का उपयोग करके उच्च जोखिम वाले क्षेत्रों की पहचान करें।',
    'gs.live_intelligence': 'लाइव इंटेलिजेंस',
    'gs.engine': 'इंजन',
    'gs.capabilities': 'क्षमताएं।',
    'ht.loading_chart': 'चार्ट लोड हो रहा है...',
    'ht.title': 'बुनियादी ढांचा स्वास्थ्य समयरेखा',
    'ht.subtitle': 'डोमेन भर में ऐतिहासिक स्थिति विश्लेषण',
    'ht.plumbing': 'नलसाजी',
    'ht.electrical': 'विद्युत',
    'ht.structural': 'संरचनात्मक',
    'ht.footer_text': 'उच्च मूल्य इष्टतम बुनियादी ढांचे की अखंडता का संकेत देते हैं (0-100 सूचकांक)'
  },
  gu: {
    'wo.title': 'ઇન્ફ્રાસ્ટ્રક્ચર ઓર્ડર',
    'wo.subtitle.contractor': 'કામગીરીના નિરાકરણ માટે ફાળવેલ કાર્યો',
    'wo.subtitle.deo': 'જિલ્લાવ્યાપી જાળવણી સોંપણીઓની દેખરેખ',
    'wo.auth_btn': 'નવો ઓર્ડર બનાવો',
    'wo.total': 'કુલ ઓર્ડર',
    'wo.active': 'સક્રિય ઓર્ડર',
    'wo.completed': 'પૂર્ણ થયેલ',
    'wo.sla': 'એસએલએ ભંગ',
    'wo.alert.title': 'એસએલએ પાલન ચેતવણી',
    'wo.alert.desc': 'અધિકૃત સમયમર્યાદા ઓળંગતા ઓર્ડર',
    'wo.tab.all': 'બધા',
    'wo.loading': 'ડેટા લોડ થઈ રહ્યો છે...',
    'wo.empty': 'કોઈ મેળ ખાતા વર્ક ઓર્ડર મળ્યા નથી.',
    'wo.th.type': 'પ્રકાર',
    'wo.th.location': 'સ્થાન',
    'wo.th.personnel': 'કર્મચારીઓ',
    'wo.th.deadline': 'અંતિમ મુદત',
    'wo.th.offset': 'વિલંબ',
    'wo.th.status': 'સ્થિતિ',
    'wo.th.actions': 'ક્રિયાઓ',
    'wo.ref': 'સંદર્ભ:',
    'wo.unknown_node': 'અજ્ઞાત સ્થાન',
    'wo.unassigned': 'સોંપેલ નથી',
    'wo.na': 'લાગુ પડતું નથી',
    'wo.breach_badge': 'એસએલએ ભંગ',
    'wo.days': 'દિવસો',
    'wo.btn.assign': 'સોંપો',
    'wo.btn.complete': 'પૂર્ણ કરો',
    'status.pending': 'બાકી',
    'status.assigned': 'સોંપાયેલ',
    'status.in_progress': 'પ્રગતિમાં',
    'status.completed': 'પૂર્ણ',
    'status.cancelled': 'રદ થયેલ',
    'deo.title': 'વહીવટી દેખરેખ કેન્દ્ર',
    'deo.subtitle': 'જિલ્લા ઈન્ફ્રાસ્ટ્રક્ચર આરોગ્ય અને અનુમાનાત્મક જાળવણી વ્યવસ્થાપન',
    'deo.all_work_orders': 'બધા વર્ક ઓર્ડર',
    'deo.assessed_schools': 'આકારણી કરેલ શાળાઓ',
    'deo.critical_risk': 'ગંભીર જોખમ',
    'deo.high_priority': 'ઉચ્ચ પ્રાથમિકતા',
    'deo.trending': 'ટ્રેન્ડિંગ',
    'deo.avg_survival': 'સરેરાશ આયુષ્ય',
    'deo.days': 'દિવસો',
    'deo.risk_queue_title': 'જોખમ સંચાલન કતાર',
    'deo.risk_queue_subtitle': 'ઈન્ફ્રાસ્ટ્રક્ચર નોડ્સનું રીઅલ-ટાઇમ પ્રિડિક્ટિવ વિશ્લેષણ',
    'deo.risk_queue_tab': 'જોખમ કતાર',
    'deo.gps_mismatches_tab': 'જીપીએસ વિસંગતતાઓ',
    'deo.filter_placeholder': 'જિલ્લો શોધો...',
    'deo.loading_scans': 'જોખમ સ્કેન લોડ થઈ રહ્યું છે...',
    'deo.no_critical_nodes': 'વર્તમાન રજિસ્ટ્રી સ્કેનમાં કોઈ ગંભીર જોખમ નોડ મળ્યા નથી.',
    'deo.score': 'સ્કોર',
    'deo.failure_horizon': 'નિષ્ફળતા ક્ષિતિજ',
    'deo.student_impact': 'વિદ્યાર્થી પ્રભાવ',
    'deo.pts': 'પોઇન્ટ્સ',
    'deo.resolve': 'ઉકેલ લાવો',
    'deo.no_mismatches': 'કોઈ સ્થાન વિસંગતતા મળી નથી',
    'deo.th.protocol': 'પ્રોટોકોલ',
    'deo.th.contractor': 'કોન્ટ્રાક્ટર / સાઇટ',
    'deo.th.coordinates': 'કોઓર્ડિનેટ્સ',
    'deo.th.alert': 'ચેતવણી',
    'deo.th.variance': 'વિવિધતા',
    'deo.verify_proof': 'પુરાવા ચકાસો',
    'deo.unknown_school': 'અજ્ઞાત શાળા',
    'deo.verified_by': 'દ્વારા ચકાસાયેલ',
    'deo.staff': 'સ્ટાફ',
    'deo.submitted': 'સબમિટ કરેલ',
    'deo.registry': 'રજિસ્ટ્રી',
    'deo.location_variance': 'સ્થાન વિસંગતતા',
    'deo.breach_detected': 'ભંગ જોવા મળ્યો',
    'deo.outside_perimeter': 'સુરક્ષા પરિમિતિની બહાર',
    'deo.last_sync': 'છેલ્લું સિંક્રનાઇઝેશન',
    'deo.security_registry_operational': 'સુરક્ષા રજિસ્ટ્રી કાર્યરત છે',
    'sv.analyzing': 'પ્રોફાઇલનું વિશ્લેષણ કરી રહ્યા છીએ...',
    'sv.access_restricted': 'પ્રવેશ પ્રતિબંધિત',
    'sv.admin_credentials_req': 'આ પ્રોફાઇલ જોવા માટે વહીવટી ઓળખપત્રો જરૂરી છે.',
    'sv.unspecified_region': 'અનિર્દિષ્ટ પ્રદેશ',
    'sv.age': 'ઉંમર',
    'sv.registry': 'રજિસ્ટ્રી',
    'sv.generic_node': 'સામાન્ય નોડ',
    'sv.admin_oversight': 'વહીવટી દેખરેખ કેન્દ્ર',
    'sv.submit_audit': 'ઓડિટ સબમિટ કરો',
    'sv.resource_registry': 'સંસાધન રજિસ્ટ્રી',
    'sv.infra_health': 'ઈન્ફ્રાસ્ટ્રક્ચર આરોગ્ય',
    'sv.global_condition': 'વૈશ્વિક સ્થિતિ અનુક્રમણિકા',
    'sv.pending_audits': 'બાકી ઓડિટ',
    'sv.due_this_month': 'આ મહિને બાકી',
    'sv.critical_risks': 'ગંભીર જોખમો',
    'sv.high_risk_vectors': 'ઉચ્ચ જોખમ વેક્ટર્સ',
    'sv.audit_history': 'ઓડિટ ઇતિહાસ',
    'sv.registry_volume': 'રજિસ્ટ્રી વોલ્યુમ',
    'sv.risk_spectrum': 'જોખમ સ્પેક્ટ્રમ',
    'sv.domain_specific': 'ડોમેન-વિશિષ્ટ મૂલ્યાંકન',
    'sv.infra_survival': 'ઈન્ફ્રાસ્ટ્રક્ચર જીવન વિશ્લેષણ',
    'sv.predictive_engine': 'અનુમાનાત્મક એનાલિટિક્સ એન્જિન',
    'sv.failure_horizon': 'નિષ્ફળતા ક્ષિતિજ',
    'sv.trend_vector': 'વલણ અને વેક્ટર',
    'sv.critical_worst': 'ગંભીર',
    'sv.none': 'કોઈ નહીં',
    'sv.insufficient_data': 'અનુમાનાત્મક જીવન વિશ્લેષણ માટે અપૂરતો ઓડિટ ડેટા.',
    'gs.cap_1_title': 'માળખાકીય આગાહી કરનાર',
    'gs.cap_1_desc': 'કોંક્રિટ અધોગતિ અને સ્લેબ તણાવની AI-સંચાલિત શોધ.',
    'gs.cap_2_title': 'અસર પ્રાથમિકતા',
    'gs.cap_2_desc': 'વિદ્યાર્થીઓના ઉપયોગ અને સુવિધાના પ્રકાર પર આધારિત સ્વચાલિત રેન્કિંગ.',
    'gs.cap_3_title': '60-દિવસની ક્ષિતિજ',
    'gs.cap_3_desc': 'પ્લમ્બિંગ અને ઇલેક્ટ્રિકલ ગ્રીડ માટે નિષ્ફળતા વિંડોની આગાહીઓ.',
    'gs.cap_4_title': '2-મિનિટ સ્ટાફ ઓડિટ',
    'gs.cap_4_desc': 'શૂન્ય મુક્ત-લખાણ ઘર્ષણ સાથે સંરચિત સાપ્તાહિક આરોગ્ય અહેવાલો.',
    'gs.cap_5_title': 'જીપીએસ ચકાસણી',
    'gs.cap_5_desc': 'જીઓ-ટેગ કરેલા દસ્તાવેજો સાથે કોન્ટ્રાક્ટર રિઝોલ્યુશન ઓડિટ.',
    'gs.cap_6_title': 'એસએલએ ટ્રેકિંગ',
    'gs.cap_6_desc': 'ફરિયાદ નિરાકરણ સમયરેખાનું વાસ્તવિક સમયનું નિરીક્ષણ.',
    'gs.cap_7_title': 'ડીઇઓ ડેશબોર્ડ',
    'gs.cap_7_desc': 'કેન્દ્રિય જિલ્લાવ્યાપી સંપત્તિ આરોગ્ય વિઝ્યુલાઇઝેશન.',
    'gs.cap_8_title': 'અનુમાનાત્મક જોખમ',
    'gs.cap_8_desc': 'મકાનની ઉંમર અને હવામાન ડેટાનો ઉપયોગ કરીને ઉચ્ચ-જોખમવાળા વિસ્તારોને ઓળખો.',
    'gs.cap_8_title': 'અનુમાનાત્મક જોખમ',
    'gs.cap_8_desc': 'મકાનની ઉંમર અને હવામાન ડેટાનો ઉપયોગ કરીને ઉચ્ચ-જોખમવાળા વિસ્તારોને ઓળખો.',
    'gs.live_intelligence': 'લાઇવ ઇન્ટેલિજન્સ',
    'gs.engine': 'એન્જિન',
    'gs.capabilities': 'ક્ષમતાઓ.',
    'ht.loading_chart': 'ચાર્ટ લોડ થઈ રહ્યો છે...',
    'ht.title': 'ઈન્ફ્રાસ્ટ્રક્ચર આરોગ્ય સમયરેખા',
    'ht.subtitle': 'ડોમેનભરમાં ઐતિહાસિક સ્થિતિ વિશ્લેષણ',
    'ht.plumbing': 'પ્લમ્બિંગ',
    'ht.electrical': 'ઇલેક્ટ્રિકલ',
    'ht.structural': 'માળખાકીય',
    'ht.footer_text': 'ઉચ્ચ મૂલ્યો શ્રેષ્ઠ ઇન્ફ્રાસ્ટ્રક્ચર અખંડિતતા દર્શાવે છે (0-100 અનુક્રમણિકા)'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('appLanguage') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
    // Optionally update document lang attribute
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
