import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  en: {
    'wo.title': 'Infrastructure Directives',
    'wo.subtitle.contractor': 'Allocated Tasks Requiring Operational Resolution',
    'wo.subtitle.deo': 'Operational Oversight of District-wide Maintenance Assignments',
    'wo.auth_btn': 'Authorize Directive',
    'wo.total': 'Total Directives',
    'wo.active': 'Active Orders',
    'wo.completed': 'Completed',
    'wo.sla': 'SLA Breaches',
    'wo.alert.title': 'SLA Compliance Alert',
    'wo.alert.desc': 'Directives exceeding authorized timelines',
    'wo.tab.all': 'ALL REGISTRY',
    'wo.loading': 'Syncing Registry...',
    'wo.empty': 'No matching work orders found in the registry.',
    'wo.th.type': 'Type',
    'wo.th.location': 'Asset Location',
    'wo.th.personnel': 'Personnel',
    'wo.th.deadline': 'Deadline',
    'wo.th.offset': 'Offset',
    'wo.th.status': 'Status',
    'wo.th.actions': 'Actions',
    'wo.ref': 'REF:',
    'wo.unknown_node': 'Unknown Node',
    'wo.unassigned': 'Unassigned',
    'wo.na': 'NA',
    'wo.breach_badge': 'SLA Breach',
    'wo.days': 'DAYS',
    'wo.btn.assign': 'Assign',
    'wo.btn.complete': 'Authorize Closure',
    'status.pending': 'Pending',
    'status.assigned': 'Assigned',
    'status.in_progress': 'In Progress',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    'wo.form.title': 'Formulate Maintenance Directive',
    'wo.form.target_node': 'Target Infrastructure Node',
    'wo.form.select_node': 'Select node...',
    'wo.form.assigned_category': 'Assigned Category',
    'wo.form.operational_priority': 'Operational Priority',
    'wo.form.objective_desc': 'Objective Description',
    'wo.form.detailed_scope': 'Detailed scope of work...',
    'wo.form.designated_personnel': 'Designated Personnel',
    'wo.form.unassigned': 'Unassigned',
    'wo.form.compliance_deadline': 'Compliance Deadline',
    'wo.form.discard': 'Discard',
    'wo.form.authorize': 'Authorize Directive',
    'priority.critical': 'Critical',
    'priority.high': 'High',
    'priority.medium': 'Medium',
    'priority.low': 'Low',
    'deo.title': 'Administrative Oversight Center',
    'deo.subtitle': 'District Infrastructure Health & Predictive Maintenance Management',
    'deo.all_work_orders': 'All Work Orders',
    'deo.assessed_schools': 'Assessed Schools',
    'deo.critical_risk': 'Critical Risk',
    'deo.high_priority': 'High Priority',
    'deo.trending': 'Trending',
    'deo.avg_survival': 'Avg Survival',
    'deo.days': 'Days',
    'deo.risk_queue_title': 'Risk Management Queue',
    'deo.risk_queue_subtitle': 'Real-time predictive analysis of infrastructure nodes',
    'deo.risk_queue_tab': 'Risk Queue',
    'deo.gps_mismatches_tab': 'GPS Mismatches',
    'deo.filter_placeholder': 'Filter District...',
    'deo.loading_scans': 'Loading Risk Scans...',
    'deo.no_critical_nodes': 'No critical risk nodes identified in current registry scan.',
    'deo.score': 'Score',
    'deo.failure_horizon': 'Failure Horizon',
    'deo.student_impact': 'Student Impact',
    'deo.pts': 'Pts',
    'deo.resolve': 'Resolve',
    'deo.no_mismatches': 'NO LOCATION MISMATCHES DETECTED',
    'deo.th.protocol': 'Protocol',
    'deo.th.contractor': 'Contractor / Site',
    'deo.th.coordinates': 'Coordinates',
    'deo.th.alert': 'Alert',
    'deo.th.variance': 'Variance',
    'deo.verify_proof': 'Verify Proof',
    'deo.unknown_school': 'Unknown School',
    'deo.verified_by': 'Verified By',
    'deo.staff': 'Staff',
    'deo.submitted': 'SUBMITTED',
    'deo.registry': 'REGISTRY',
    'deo.location_variance': 'Location Variance',
    'deo.breach_detected': 'Breach Detected',
    'deo.outside_perimeter': 'Outside Security Perimeter',
    'deo.last_sync': 'Last Synchronization',
    'deo.security_registry_operational': 'Security Registry Operational',
    'sv.analyzing': 'Analysing Profile...',
    'sv.access_restricted': 'Access Restricted',
    'sv.admin_credentials_req': 'Administrative credentials required to view this profile.',
    'sv.unspecified_region': 'Unspecified Region',
    'sv.age': 'Age',
    'sv.registry': 'Registry',
    'sv.generic_node': 'Principal Dashboard',
    'sv.admin_oversight': 'Administrative Oversight Center',
    'sv.submit_audit': 'Submit Audit',
    'sv.resource_registry': 'Resource Registry',
    'sv.infra_health': 'Infrastructure Health',
    'sv.global_condition': 'Global condition index',
    'sv.pending_audits': 'Pending Audits',
    'sv.due_this_month': 'due this month',
    'sv.critical_risks': 'Critical Risks',
    'sv.high_risk_vectors': 'High risk vectors',
    'sv.audit_history': 'Audit History',
    'sv.registry_volume': 'Registry Volume',
    'sv.risk_spectrum': 'Risk Spectrum',
    'sv.domain_specific': 'Domain-specific assessment',
    'sv.infra_survival': 'Infrastructure Survival Analysis',
    'sv.predictive_engine': 'Predictive Analytics Engine',
    'sv.failure_horizon': 'Failure Horizon',
    'sv.trend_vector': 'Trend & Vector',
    'sv.critical_worst': 'Critical',
    'sv.none': 'None',
    'sv.insufficient_data': 'Insufficient audit data for predictive survival analysis.',
    'gs.cap_1_title': 'Structural Forecaster',
    'gs.cap_1_desc': 'AI-driven detection of concrete degradation and slab stress.',
    'gs.cap_2_title': 'Impact Priority',
    'gs.cap_2_desc': 'Automatic ranking based on student usage and facility type.',
    'gs.cap_3_title': '60-Day Horizon',
    'gs.cap_3_desc': 'Failure window predictions for plumbing and electrical grids.',
    'gs.cap_4_title': '2-Min Staff Audit',
    'gs.cap_4_desc': 'Structured weekly health reports with zero free-text friction.',
    'gs.cap_5_title': 'GPS Verification',
    'gs.cap_5_desc': 'Contractor resolution audits with geo-tagged documentation.',
    'gs.cap_6_title': 'SLA Tracking',
    'gs.cap_6_desc': 'Real-time monitoring of complaint resolution timelines.',
    'gs.cap_7_title': 'DEO Dashboard',
    'gs.cap_7_desc': 'Centralized district-wide asset health view.',
    'gs.cap_8_title': 'Predictive Risk',
    'gs.cap_8_desc': 'Identify high-risk zones using building age and weather data.',
    'gs.live_intelligence': 'Live Intelligence',
    'gs.engine': 'Engine',
    'gs.capabilities': 'Capabilities.',
    'gs.map_filters': 'Map Filters',
    'gs.show_all_sites': 'Show All Sites',
    'gs.critical_only': '🔴 Critical Only',
    'gs.recenter': 'Recenter to my location',
    'gs.title': 'Infrastructure Mapping Grid',
    'gs.subtitle': 'Geospatial monitoring of structural risk baseline across regions',
    'gs.all_districts': 'All Districts',
    'gs.update': 'Update',
    'gs.id_nodes': 'Identification Nodes',
    'gs.critical_desig': 'Critical Designation',
    'gs.stable_baseline': 'Stable Baseline',
    'gs.nav_target': 'Navigating To Target',
    'gs.distance': 'Distance',
    'gs.km': 'km',
    'gs.est_eta': 'Est. ETA',
    'gs.min': 'min',
    'gs.cancel_nav': 'Cancel Navigation',
    'gs.syncing_gps': 'Syncing GPS Nodes...',
    'gs.designation': 'Designation',
    'gs.routing': 'Routing...',
    'gs.get_directions': 'Get Directions',
    'gs.view_profile': 'View Full Profile',
    'gs.user_node': 'User Node',
    'gs.gps_active': 'Operational GPS Active',
    'gs.access_denied': 'Access Denied.',
    'gs.alert_location': 'Please allow location access to get directions.',
    'gs.alert_route_fail': 'Could not calculate route.',
    'gs.alert_fetch_fail': 'Failed to fetch route.',
    'alv.access_denied': 'Access Denied',
    'alv.title': 'System Audit Log',
    'alv.subtitle': 'Immutable record of all platform actions',
    'alv.actor_role': 'Actor Role',
    'alv.all_roles': 'All Roles',
    'alv.action_sig': 'Action Signature',
    'alv.filter_action': 'Filter by event name...',
    'alv.window_start': 'Log Window Start',
    'alv.window_end': 'Log Window End',
    'alv.apply_filters': 'Apply Filters',
    'alv.th_timestamp': 'Timestamp',
    'alv.th_actor': 'Actor',
    'alv.th_role': 'Role',
    'alv.th_action': 'Action Signature',
    'alv.th_target': 'Resource Target',
    'alv.th_details': 'Details',
    'alv.syncing': 'Synchronizing Logs...',
    'alv.no_events': 'No matching audit events found in the immutable registry.',
    'alv.unknown_actor': 'Unknown Actor',
    'alv.unknown_role': 'Unknown',
    'alv.general_system': 'General System',
    'alv.payload': 'Payload',
    'alv.extracted_metadata': 'EXTRACTED METADATA',
    'alv.registry_page': 'Registry Page',
    'alv.events': 'Events',
    'nav.features': 'Features',
    'nav.how_it_works': 'How It Works',
    'nav.app_preview': 'App Preview',
    'nav.dashboard': 'Dashboard',
    'nav.login': 'Login',
    'hero.scan': 'STRUCTURAL_SCAN',
    'hero.health_index': 'Health Index',
    'hero.high_risk': 'HIGH RISK',
    'hero.prediction_engine': 'PREDICTION ENGINE',
    'hero.forecast_horizon': 'Forecast Horizon',
    'hero.priority_active': 'PRIORITY_ACTIVE',
    'hero.ranked_impact': 'Ranked #1 for Student Impact',
    'hero.audit_ready': 'Audit Ready',
    'hero.secure_core': 'SECURE_CORE_ACTIVE',
    'hero.built_to': 'Built To',
    'hero.typewriter_1': 'Predict.',
    'hero.typewriter_2': 'Repair.',
    'hero.typewriter_3': 'Secure.',
    'hero.typewriter_4': 'Maintain.',
    'hero.description': 'AI-driven infrastructure intelligence for 30,000+ schools. Detect failures 60 days ahead with automated impact ranking.',
    'hero.enter_portal': 'Enter Portal',
    'hero.view_logs': 'View Logs',
    'feat.infra_intel': 'Infrastructure Intelligence',
    'feat.predictive_core': 'Predictive Core.',
    'feat.structural_precision': 'Structural Precision.',
    'feat.multi_factor': 'Multi-Factor Forecast',
    'feat.multi_factor_desc': 'Forecast failure windows for 30,000+ buildings using building age, material, and weather zone data.',
    'feat.structural': 'STRUCTURAL',
    'feat.plumbing': 'PLUMBING',
    'feat.electrical': 'ELECTRICAL',
    'feat.impact_bias': 'Impact Bias Queue',
    'feat.impact_desc': "Automatic ranking system: Girls' school toilet repairs rank above cracked storage room walls.",
    'feat.two_min_audits': '2-Min Audits',
    'feat.two_min_desc': 'Structured weekly condition forms—completable in under 2 minutes by school staff.',
    'feat.compliant': '% Compliant',
    'preview.asset_health': 'Asset Health',
    'preview.live_prediction': 'Live Prediction Engine',
    'preview.total_control': 'Total control.',
    'preview.bespoke_telemetry': 'Bespoke telemetry.',
    'preview.risk_factor': 'RISK FACTOR',
    'preview.infra_zone': 'Infrastructure Zone A-12',
    'preview.remaining': 'REMAINING',
    'preview.status': 'STATUS',
    'preview.active': 'ACTIVE',
    'preview.dispatch_team': 'DISPATCH TEAM',
    'preview.priority_zone': 'PRIORITY ZONE',
    'preview.model_school': 'Model School #04',
    'preview.verified': 'VERIFIED',
    'preview.annual_audit': 'ANNUAL AUDIT',
    'preview.safety_pass': 'Safety Pass',
    'hiw.report': 'REPORT',
    'hiw.field_data': 'FIELD_DATA',
    'hiw.report_desc': 'School staff submits structured weekly reports on asset conditions in under 2 minutes.',
    'hiw.forecast': 'FORECAST',
    'hiw.ai_analysis': 'AI_ANALYSIS',
    'hiw.forecast_desc': "Saksham's AI models analyze the data to predict infrastructure failures within a 30-60 day window.",
    'hiw.rank': 'RANK',
    'hiw.impact_priority': 'IMPACT_PRIORITY',
    'hiw.rank_desc': "The system prioritizes repairs based on student impact, ranking critical facilities like girls' toilets first.",
    'hiw.resolve': 'RESOLVE',
    'hiw.audit_done': 'AUDIT_DONE',
    'hiw.resolve_desc': 'Maintenance crews are dispatched, and the final resolution is verified with before/after documentation.',
    'hiw.cycle': 'The Predictive Cycle',
    'hiw.predicting_to': 'Predicting To',
    'hiw.protect_safety': 'Protect Safety.',
    'hiw.desc': 'We transitioned from reactive repairs to predictive maintenance, ensuring school assets are always secure.',
    'testi.title_1': 'District Officers',
    'testi.desc_1': 'A centralized dashboard for DEOs to monitor prioritized maintenance queues based on real-world student impact scores.',
    'testi.title_2': 'Field Reporting',
    'testi.desc_2': 'Optimized mobile forms for school staff to complete structural health checks in under 2 minutes.',
    'testi.title_3': 'Contractor Sync',
    'testi.desc_3': 'Automated work orders with before/after verification and GPS-tagged resolution audits.',
    'testi.title_4': 'Predictive Analytics',
    'testi.desc_4': 'AI models forecasting failure windows for plumbing, electrical, and structural systems 30-60 days in advance.',
    'testi.built_for': 'Built for Every',
    'testi.institution': 'Institution.',
    'dl.schools_monitored': 'SCHOOLS_MONITORED',
    'dl.terminal_ready': 'Field Terminal Ready',
    'dl.title': 'The Audit App.',
    'dl.subtitle': 'In Every School.',
    'dl.desc': 'Empower school staff with a structured auditing tool. Submit weekly condition reports in under 2 minutes with real-time sync.',
    'dl.download_on': 'Download on',
    'dl.get_it_on': 'Get it on',
    'dl.scan_for': 'SCAN FOR',
    'dl.sync_active': 'AUDIT_SYNC_ACTIVE',
    'foot.op_mode': 'Operational_Mode',
    'foot.predictive_live': 'PREDICTIVE_LIVE',
    'foot.uptime': 'Uptime_Protocol',
    'foot.node_status': 'Node_Status',
    'foot.gujarat_west': 'GUJARAT_WEST_01',
    'foot.api_core': 'API_Core',
    'foot.v2_stable': 'v2.4.0_STABLE',
    'foot.desc': 'The definitive predictive maintenance engine for institutional infrastructure. Data-driven safety for every classroom.',
    'foot.useful_links': 'Useful Links',
    'foot.about': 'About Us',
    'foot.features': 'Features',
    'foot.app_preview': 'App Preview',
    'foot.pricing': 'Pricing',
    'foot.legal_support': 'Legal & Support',
    'foot.privacy': 'Privacy Policy',
    'foot.terms': 'Terms of Service',
    'foot.system_status': 'System Status',
    'foot.contact': 'Contact Support',
    'foot.stay_updated': 'Stay Updated',
    'foot.stay_updated_desc': 'Get the latest infrastructure insights and system updates.',
    'foot.enter_email': 'Enter email address',
    'foot.subscribe': 'SUBSCRIBE NOW',
    'foot.made_in': 'Made with ❤️ in India.',
    'foot.copyright': 'Copyright ©',
    'login.role_admin': 'System Admin',
    'login.role_deo': 'District Officer',
    'login.role_principal': 'School Principal',
    'login.role_contractor': 'Contractor',
    'login.role_peon': 'School Peon',
    'login.predictive_engine': 'Predictive Engine v3',
    'login.welcome': 'Welcome To',
    'login.the_core': 'The Core.',
    'login.desc': 'Secure Access Gateway. Authenticate your identity to access the predictive infrastructure dashboard.',
    'login.system_secure': 'System Secure',
    'login.encrypted_conn': 'Encrypted Connection',
    'login.system_operational': 'System Operational',
    'login.auth_title': 'Authenticate.',
    'login.auth_subtitle': 'Enter credentials to access portal',
    'login.invalid_creds': 'Invalid credentials. Please try again.',
    'login.email_label': 'Identity / Email Address',
    'login.password_label': 'Secure Password',
    'login.authenticate_btn': 'Authenticate',
    'login.sandbox_identities': 'Sandbox Identities · password: password123',
    'login.need_access': 'Need infrastructure access? ',
    'login.request_profile': 'Request Profile',
    'signup.role_peon': 'School Peon',
    'signup.role_principal': 'School Principal',
    'signup.role_deo': 'DEO',
    'signup.role_contractor': 'Contractor',
    'signup.role_admin': 'Admin',
    'signup.predictive_engine': 'Predictive Engine v3',
    'signup.build_the': 'Build The',
    'signup.infrastructure': 'Infrastructure',
    'signup.of_tomorrow': 'Of Tomorrow.',
    'signup.desc': 'Join the predictive maintenance network securing over 30,000+ schools. Stop failures before they happen.',
    'signup.high_risk': 'High Risk Detected',
    'signup.structural_block': 'Structural Block B',
    'signup.system_operational': 'System Operational',
    'signup.init_title': 'Initialize.',
    'signup.init_subtitle': 'Set up your clearance profile',
    'signup.password_mismatch': 'Passwords do not match',
    'signup.reg_failed': 'Registration failed. Try again.',
    'signup.select_access': 'Select Access Level (RBAC)',
    'signup.full_name': 'Full Name',
    'signup.email': 'Email Address',
    'signup.contact_number': 'Contact Number',
    'signup.district': 'District Jurisdiction',
    'signup.school_id': 'Canonical School ID',
    'signup.password': 'Secure Password',
    'signup.confirm_password': 'Confirm Secret',
    'signup.authorize': 'Authorize Clearance',
    'signup.already_have': 'Already have clearance? ',
    'signup.return_hub': 'Return to Hub',
    'peon.title': 'Condition Audit Form (Weekly)',
    'peon.ref': 'Ref',
    'peon.week': 'Week',
    'peon.instruction_title': 'Instruction for School Personnel',
    'peon.instruction_desc': 'Please provide accurate physical assessments for each category. Uploading a clear photo of identifiable issues is mandatory for priority maintenance allocation.',
    'peon.cat_plumbing': 'Plumbing',
    'peon.cat_electrical': 'Electrical',
    'peon.cat_structural': 'Structural',
    'peon.unit_assessment': 'Unit Assessment',
    'peon.condition_state': 'Condition State (1-5)',
    'peon.required': 'Required',
    'peon.score_1': 'EXCELLENT',
    'peon.score_2': 'GOOD',
    'peon.score_3': 'FAIR',
    'peon.score_4': 'POOR',
    'peon.score_5': 'CRITICAL',
    'peon.deficiency_list': 'Deficiency Check-list',
    'peon.toilet_1_0': 'All Functional',
    'peon.toilet_0_75': 'Mostly Functional',
    'peon.toilet_0_5': 'Partially Functional',
    'peon.toilet_0_25': 'Few Functional',
    'peon.toilet_0_0': 'None Functional',
    'peon.power_0': 'No Outage',
    'peon.power_3': 'Minimal',
    'peon.power_8': 'Notable',
    'peon.power_15': 'Significant',
    'peon.power_25': 'Critical',
    'peon.crack_0': 'No Cracks',
    'peon.crack_0_5': 'Hairline',
    'peon.crack_2': 'Minor',
    'peon.crack_6': 'Moderate',
    'peon.crack_15': 'Major',
    'peon.crack_25': 'Severe',
    'peon.flag_waterLeak': 'Water Leak',
    'peon.flag_brokenTap': 'Broken Tap',
    'peon.flag_cloggedDrain': 'Clogged Drain',
    'peon.flag_tankOverflow': 'Tank Overflow',
    'peon.flag_lowWaterPressure': 'Low Pressure',
    'peon.flag_wallSeepage': 'Wall Seepage',
    'peon.flag_roofLeakFlag': 'Roof Leak',
    'peon.flag_brokenDoor': 'Broken Door',
    'peon.flag_pestInfestation': 'Pest Issues',
    'peon.flag_issueFlag': 'Other Issue',
    'peon.flag_wiringExposed': 'Exposed Wiring',
    'peon.flag_brokenSwitch': 'Broken Switch',
    'peon.flag_burntSocket': 'Burnt Socket',
    'peon.flag_flickeringLights': 'Flickering',
    'peon.flag_panelDamage': 'Panel Damage',
    'peon.flag_highVoltage': 'Voltage Surge',
    'peon.flag_brokenWindow': 'Broken Window',
    'peon.flag_paintPeeling': 'Paint Peeling',
    'peon.flag_floorDamage': 'Floor Cracks',
    'peon.flag_ceilingHole': 'Ceiling Hole',
    'peon.observe': 'Observe and Select...',
    'peon.submit_report': 'Submit Audit Report',
    'peon.photo_evidence': 'Evidence Photography',
    'peon.photo_success': 'Image captured successfully',
    'peon.photo_select': 'Select Inspection Photo',
    'peon.photo_format': 'JPG, PNG allowed (Max 5MB)',
    'ht.loading_chart': 'Loading Chart...',
    'ht.title': 'Infrastructure Health Timeline',
    'ht.subtitle': 'Historical condition analysis across domains',
    'ht.plumbing': 'Plumbing',
    'ht.electrical': 'Electrical',
    'ht.structural': 'Structural',
    'ht.footer_text': 'Higher values indicate optimal infrastructure integrity (0-100 index)',
    'deo.view_evidence': 'View Evidence',
    'nav.principal_dashboard': 'Principal Dashboard',
    'nav.view_reports': 'View Reports',
    'nav.predictive_queue': 'Predictive Queue',
    'nav.forwarded_reports': 'Forwarded Reports',
    'nav.live_map': 'Live Map',
    'nav.command_center': 'Command Center',
    'nav.field_console': 'Field Console',
    'nav.all_orders': 'All Orders',
    'nav.admin_panel': 'Admin Panel',
    'nav.audit_log': 'Audit Log',
    'role.peon': 'Peon/Watchman',
    'role.principal': 'Principal',
    'role.deo': 'DEO COMMAND',
    'role.contractor': 'Contractor',
    'role.admin': 'System Admin',
    'role.school': 'School',
    'fr.title': 'Forwarded School Reports',
    'fr.subtitle': 'Bundles forwarded by principals · ranked by LR urgency',
    'fr.bundle': 'Bundle',
    'fr.bundles': 'Bundles',
    'fr.view_all': 'View All',
    'fr.loading': 'Loading forwarded bundles…',
    'fr.no_reports': 'No reports have been forwarded by principals yet.',
    'fr.week_abbr': 'W',
    'fr.30_day_fail': '30-DAY FAIL',
    'fr.worst': 'Worst',
    'fr.forwarded': 'Forwarded',
    'fr.lr_urgency': 'LR Urgency',
    'fr.pdf': 'PDF',
    'fr.assign': 'Assign',
    'fr.more_bundles': 'more bundles · View all',
    'nav.logout': 'Logout',
    'clv.photo_on_file': 'Photo on file',
    'clv.lr_urgency': 'LR Urgency',
    'clv.days_to_failure': 'Days to Failure',
    'clv.week': 'Week',
    'clv.weekly_bundle': 'Weekly Bundle',
    'clv.categories': 'categories',
    'clv.category': 'category',
    'clv.worst': 'Worst',
    'clv.submitted': 'Submitted',
    'clv.lr_urgency_score': 'LR Urgency Score',
    'clv.view_pdf': 'View PDF',
    'clv.sent_to_deo': 'SENT TO DEO',
    'clv.send_to_deo': 'Send to DEO',
    'clv.assign_contractor': 'Assign Contractor',
    'clv.lr_model_output': 'LR model output (TS-PS3.csv trained)',
    'clv.forwarded_to_deo_on': 'Forwarded to DEO on',
    'clv.loading_reports': 'Loading Reports...',
    'clv.access_restricted': 'Access Restricted',
    'clv.auth_required': 'Principal or DEO authorization is required for this view.',
    'clv.account_unlinked': 'Account Unlinked',
    'clv.no_school': 'Your principal account is not associated with a school.',
    'clv.deo_title': 'Forwarded Weekly Reports',
    'clv.prin_title': 'Weekly Condition Reports',
    'clv.deo_subtitle': 'Bundles forwarded by school principals — ranked by LR urgency, most urgent on top',
    'clv.prin_subtitle': 'Bundled per-week assessments — each card runs the trained LR model and bundles all 3 categories',
    'clv.total_bundles': 'Total Weekly Bundles',
    'clv.critical_urgency': 'Critical Urgency',
    'clv.predicted_fail': 'Predicted Fail < 30d',
    'clv.sent_to_deo_stat': 'Sent to DEO',
    'clv.pending': 'pending',
    'clv.refine_view': 'Refine View:',
    'clv.any_urgency': 'Any urgency',
    'clv.all_bundles': 'All bundles',
    'clv.awaiting_deo': 'Awaiting DEO',
    'clv.sent_filter': 'Sent to DEO',
    'clv.bundles_sorted': 'Bundles · Sorted by LR Urgency',
    'clv.lr_reports': 'Weekly Reports (LR-prioritised)',
    'clv.one_card': 'One card per week — most urgent on top',
    'clv.no_reports': 'No weekly reports submitted yet.',
    'clv.no_match': 'No bundles match the current filters.',
    'clv.forwarding': 'Forwarding Week'
  },
  hi: {
    'wo.title': 'बुनियादी ढांचा निर्देश',
    'wo.subtitle.contractor': 'कार्यात्मक समाधान की आवश्यकता वाले आवंटित कार्य',
    'wo.subtitle.deo': 'जिले भर के रखरखाव कार्यों की परिचालन निगरानी',
    'wo.auth_btn': 'नया निर्देश बनाएं',
    'wo.total': 'कुल निर्देश',
    'wo.active': 'सक्रिय आदेश',
    'wo.completed': 'पूर्ण',
    'wo.sla': 'SLA उल्लंघन',
    'wo.alert.title': 'SLA अनुपालन चेतावनी',
    'wo.alert.desc': 'अधिकृत समय सीमा पार करने वाले निर्देश',
    'wo.tab.all': 'सभी',
    'wo.loading': 'डेटा सिंक हो रहा है...',
    'wo.empty': 'कोई मेल खाने वाले कार्य आदेश नहीं मिले।',
    'wo.th.type': 'प्रकार',
    'wo.th.location': 'स्थान',
    'wo.th.personnel': 'कर्मचारी',
    'wo.th.deadline': 'समय सीमा',
    'wo.th.offset': 'विलंब',
    'wo.th.status': 'स्थिति',
    'wo.th.actions': 'कार्रवाइयां',
    'wo.ref': 'संदर्भ:',
    'wo.unknown_node': 'अज्ञात स्थान',
    'wo.unassigned': 'कोई नहीं',
    'wo.na': 'लागू नहीं',
    'wo.breach_badge': 'SLA उल्लंघन',
    'wo.days': 'दिन',
    'wo.btn.assign': 'सौंपें',
    'wo.btn.complete': 'पूर्ण करें',
    'status.pending': 'लंबित',
    'status.assigned': 'सौंपा गया',
    'status.in_progress': 'प्रगति पर',
    'status.completed': 'पूरा हुआ',
    'status.cancelled': 'रद्द किया गया',
    'wo.form.title': 'रखरखाव निर्देश तैयार करें',
    'wo.form.target_node': 'लक्ष्य बुनियादी ढांचा नोड',
    'wo.form.select_node': 'नोड चुनें...',
    'wo.form.assigned_category': 'निर्दिष्ट श्रेणी',
    'wo.form.operational_priority': 'परिचालन प्राथमिकता',
    'wo.form.objective_desc': 'उद्देश्य विवरण',
    'wo.form.detailed_scope': 'कार्य का विस्तृत दायरा...',
    'wo.form.designated_personnel': 'नामित कर्मी',
    'wo.form.unassigned': 'अनिर्दिष्ट',
    'wo.form.compliance_deadline': 'अनुपालन समय सीमा',
    'wo.form.discard': 'रद्द करें',
    'wo.form.authorize': 'निर्देश अधिकृत करें',
    'priority.critical': 'गंभीर',
    'priority.high': 'उच्च',
    'priority.medium': 'मध्यम',
    'priority.low': 'निम्न',
    'deo.title': 'प्रशासनिक निरीक्षण केंद्र',
    'deo.subtitle': 'जिला बुनियादी ढांचा स्वास्थ्य और भविष्य कहनेवाला रखरखाव प्रबंधन',
    'deo.all_work_orders': 'सभी कार्य आदेश',
    'deo.assessed_schools': 'आंकलित स्कूल',
    'deo.critical_risk': 'गंभीर जोखिम',
    'deo.high_priority': 'उच्च प्राथमिकता',
    'deo.trending': 'रुझान',
    'deo.avg_survival': 'औसत जीवन',
    'deo.days': 'दिन',
    'deo.risk_queue_title': 'जोखिम प्रबंधन कतार',
    'deo.risk_queue_subtitle': 'बुनियादी ढांचे के नोड्स का वास्तविक समय पूर्वानुमान विश्लेषण',
    'deo.risk_queue_tab': 'जोखिम कतार',
    'deo.gps_mismatches_tab': 'जीपीएस विसंगतियां',
    'deo.filter_placeholder': 'जिला खोजें...',
    'deo.loading_scans': 'जोखिम स्कैन लोड हो रहा है...',
    'deo.no_critical_nodes': 'वर्तमान रजिस्ट्री स्कैन में कोई गंभीर जोखिम नोड नहीं मिला।',
    'deo.score': 'स्कोर',
    'deo.failure_horizon': 'विफलता सीमा',
    'deo.student_impact': 'छात्र प्रभाव',
    'deo.pts': 'अंक',
    'deo.resolve': 'समाधान करें',
    'deo.no_mismatches': 'कोई स्थान विसंगति नहीं मिली',
    'deo.th.protocol': 'प्रोटोकॉल',
    'deo.th.contractor': 'ठेकेदार / साइट',
    'deo.th.coordinates': 'निर्देशांक',
    'deo.th.alert': 'चेतावनी',
    'deo.th.variance': 'भिन्नता',
    'deo.verify_proof': 'प्रमाण सत्यापित करें',
    'deo.unknown_school': 'अज्ञात स्कूल',
    'deo.verified_by': 'द्वारा सत्यापित',
    'deo.staff': 'स्टाफ',
    'deo.submitted': 'प्रस्तुत',
    'deo.registry': 'रजिस्ट्री',
    'deo.location_variance': 'स्थान भिन्नता',
    'deo.breach_detected': 'उल्लंघन का पता चला',
    'deo.outside_perimeter': 'सुरक्षा परिधि के बाहर',
    'deo.last_sync': 'अंतिम सिंक्रनाइज़ेशन',
    'deo.security_registry_operational': 'सुरक्षा रजिस्ट्री चालू है',
    'sv.analyzing': 'प्रोफ़ाइल का विश्लेषण कर रहा है...',
    'sv.access_restricted': 'पहुंच प्रतिबंधित',
    'sv.admin_credentials_req': 'इस प्रोफ़ाइल को देखने के लिए प्रशासनिक क्रेडेंशियल आवश्यक हैं।',
    'sv.unspecified_region': 'अनिर्दिष्ट क्षेत्र',
    'sv.age': 'आयु',
    'sv.registry': 'रजिस्ट्री',
    'sv.generic_node': 'प्रिंसिपल डैशबोर्ड',
    'sv.admin_oversight': 'प्रशासनिक निरीक्षण केंद्र',
    'sv.submit_audit': 'ऑडिट जमा करें',
    'sv.resource_registry': 'संसाधन रजिस्ट्री',
    'sv.infra_health': 'बुनियादी ढांचा स्वास्थ्य',
    'sv.global_condition': 'वैश्विक स्थिति सूचकांक',
    'sv.pending_audits': 'लंबित ऑडिट',
    'sv.due_this_month': 'इस महीने देय',
    'sv.critical_risks': 'गंभीर जोखिम',
    'sv.high_risk_vectors': 'उच्च जोखिम वैक्टर',
    'sv.audit_history': 'ऑडिट इतिहास',
    'sv.registry_volume': 'रजिस्ट्री वॉल्यूम',
    'sv.risk_spectrum': 'जोखिम स्पेक्ट्रम',
    'sv.domain_specific': 'डोमेन-विशिष्ट मूल्यांकन',
    'sv.infra_survival': 'बुनियादी ढांचा जीवन विश्लेषण',
    'sv.predictive_engine': 'भविष्य कहनेवाला विश्लेषिकी इंजन',
    'sv.failure_horizon': 'विफलता सीमा',
    'sv.trend_vector': 'रुझान और वेक्टर',
    'sv.critical_worst': 'गंभीर',
    'sv.none': 'कोई नहीं',
    'sv.insufficient_data': 'भविष्य कहनेवाला जीवन विश्लेषण के लिए अपर्याप्त ऑडिट डेटा।',
    'gs.cap_1_title': 'संरचनात्मक पूर्वानुमानकर्ता',
    'gs.cap_1_desc': 'कंक्रीट क्षरण और स्लैब तनाव का एआई-संचालित पता लगाना।',
    'gs.cap_2_title': 'प्रभाव प्राथमिकता',
    'gs.cap_2_desc': 'छात्र उपयोग और सुविधा प्रकार के आधार पर स्वचालित रैंकिंग।',
    'gs.cap_3_title': '60-दिन की सीमा',
    'gs.cap_3_desc': 'पाइपलाइन और विद्युत ग्रिड के लिए विफलता खिड़की की भविष्यवाणी।',
    'gs.cap_4_title': '2-मिनट स्टाफ ऑडिट',
    'gs.cap_4_desc': 'शून्य मुक्त-पाठ घर्षण के साथ संरचित साप्ताहिक स्वास्थ्य रिपोर्ट।',
    'gs.cap_5_title': 'जीपीएस सत्यापन',
    'gs.cap_5_desc': 'जियो-टैग किए गए दस्तावेज़ों के साथ ठेकेदार समाधान ऑडिट।',
    'gs.cap_6_title': 'SLA ट्रैकिंग',
    'gs.cap_6_desc': 'शिकायत समाधान समयसीमा की वास्तविक समय की निगरानी।',
    'gs.cap_7_title': 'DEO डैशबोर्ड',
    'gs.cap_7_desc': 'केंद्रीकृत जिला-व्यापी संपत्ति स्वास्थ्य दृश्य।',
    'gs.cap_8_title': 'भविष्य कहनेवाला जोखिम',
    'gs.cap_8_desc': 'इमारत की उम्र और मौसम के डेटा का उपयोग करके उच्च जोखिम वाले क्षेत्रों की पहचान करें।',
    'gs.live_intelligence': 'लाइव इंटेलिजेंस',
    'gs.engine': 'इंजन',
    'gs.capabilities': 'क्षमताएं।',
    'gs.map_filters': 'मानचित्र फ़िल्टर',
    'gs.show_all_sites': 'सभी साइटें दिखाएं',
    'gs.critical_only': '🔴 केवल गंभीर',
    'gs.recenter': 'मेरे स्थान पर फिर से केंद्रित करें',
    'gs.title': 'बुनियादी ढांचा मानचित्रण ग्रिड',
    'gs.subtitle': 'क्षेत्रों में संरचनात्मक जोखिम आधार रेखा की भू-स्थानिक निगरानी',
    'gs.all_districts': 'सभी जिले',
    'gs.update': 'अपडेट करें',
    'gs.id_nodes': 'पहचान नोड',
    'gs.critical_desig': 'गंभीर पदनाम',
    'gs.stable_baseline': 'स्थिर आधार रेखा',
    'gs.nav_target': 'लक्ष्य की ओर नेविगेट कर रहा है',
    'gs.distance': 'दूरी',
    'gs.km': 'किमी',
    'gs.est_eta': 'अनुमानित ईटीए',
    'gs.min': 'मिनट',
    'gs.cancel_nav': 'नेविगेशन रद्द करें',
    'gs.syncing_gps': 'GPS नोड्स को सिंक कर रहा है...',
    'gs.designation': 'पदनाम',
    'gs.routing': 'रूटिंग...',
    'gs.get_directions': 'दिशा-निर्देश प्राप्त करें',
    'gs.view_profile': 'पूरी प्रोफ़ाइल देखें',
    'gs.user_node': 'उपयोगकर्ता नोड',
    'gs.gps_active': 'परिचालन GPS सक्रिय',
    'gs.access_denied': 'पहुँच से इनकार।',
    'gs.alert_location': 'कृपया दिशा-निर्देश प्राप्त करने के लिए स्थान पहुंच की अनुमति दें।',
    'gs.alert_route_fail': 'रूट की गणना नहीं की जा सकी।',
    'gs.alert_fetch_fail': 'रूट लाने में विफल।',
    'alv.access_denied': 'पहुंच अस्वीकृत',
    'alv.title': 'सिस्टम ऑडिट लॉग',
    'alv.subtitle': 'सभी प्लेटफ़ॉर्म क्रियाओं का अपरिवर्तनीय रिकॉर्ड',
    'alv.actor_role': 'अभिनेता की भूमिका',
    'alv.all_roles': 'सभी भूमिकाएँ',
    'alv.action_sig': 'कार्रवाई हस्ताक्षर',
    'alv.filter_action': 'ईवेंट नाम से फ़िल्टर करें...',
    'alv.window_start': 'लॉग विंडो प्रारंभ',
    'alv.window_end': 'लॉग विंडो अंत',
    'alv.apply_filters': 'फ़िल्टर लागू करें',
    'alv.th_timestamp': 'समय मोहर',
    'alv.th_actor': 'अभिनेता',
    'alv.th_role': 'भूमिका',
    'alv.th_action': 'कार्रवाई हस्ताक्षर',
    'alv.th_target': 'संसाधन लक्ष्य',
    'alv.th_details': 'विवरण',
    'alv.syncing': 'लॉग सिंक कर रहा है...',
    'alv.no_events': 'अपरिवर्तनीय रजिस्ट्री में कोई मेल खाने वाले ऑडिट ईवेंट नहीं मिले।',
    'alv.unknown_actor': 'अज्ञात अभिनेता',
    'alv.unknown_role': 'अज्ञात',
    'alv.general_system': 'सामान्य प्रणाली',
    'alv.payload': 'पेलोड',
    'alv.extracted_metadata': 'निकाला गया मेटाडेटा',
    'alv.registry_page': 'रजिस्ट्री पृष्ठ',
    'alv.events': 'ईवेंट',
    'nav.features': 'विशेषताएं',
    'nav.how_it_works': 'यह कैसे काम करता है',
    'nav.app_preview': 'ऐप पूर्वावलोकन',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.login': 'लॉगिन',
    'hero.scan': 'संरचनात्मक_स्कैन',
    'hero.health_index': 'स्वास्थ्य सूचकांक',
    'hero.high_risk': 'उच्च जोखिम',
    'hero.prediction_engine': 'भविष्यवाणी इंजन',
    'hero.forecast_horizon': 'पूर्वानुमान क्षितिज',
    'hero.priority_active': 'प्राथमिकता_सक्रिय',
    'hero.ranked_impact': 'छात्र प्रभाव के लिए # 1 स्थान पर है',
    'hero.audit_ready': 'ऑडिट तैयार',
    'hero.secure_core': 'सुरक्षित_कोर_सक्रिय',
    'hero.built_to': 'के लिए बनाया गया',
    'hero.typewriter_1': 'भविष्यवाणी.',
    'hero.typewriter_2': 'मरम्मत.',
    'hero.typewriter_3': 'सुरक्षित.',
    'hero.typewriter_4': 'बनाए रखना.',
    'hero.description': '30,000+ स्कूलों के लिए एआई-संचालित बुनियादी ढांचा बुद्धिमत्ता। स्वचालित प्रभाव रैंकिंग के साथ 60 दिन पहले विफलताओं का पता लगाएं।',
    'hero.enter_portal': 'पोर्टल दर्ज करें',
    'hero.view_logs': 'लॉग देखें',
    'feat.infra_intel': 'बुनियादी ढांचा बुद्धिमत्ता',
    'feat.predictive_core': 'भविष्य कहनेवाला कोर.',
    'feat.structural_precision': 'संरचनात्मक परिशुद्धता.',
    'feat.multi_factor': 'बहु-कारक पूर्वानुमान',
    'feat.multi_factor_desc': 'इमारत की उम्र, सामग्री और मौसम क्षेत्र डेटा का उपयोग करके 30,000+ इमारतों के लिए विफलता खिड़कियों का पूर्वानुमान लगाएं।',
    'feat.structural': 'संरचनात्मक',
    'feat.plumbing': 'प्लंबिंग',
    'feat.electrical': 'विद्युत',
    'feat.impact_bias': 'प्रभाव पूर्वाग्रह कतार',
    'feat.impact_desc': 'स्वचालित रैंकिंग प्रणाली: लड़कियों के स्कूल के शौचालय की मरम्मत फटी हुई भंडारण कक्ष की दीवारों से ऊपर होती है।',
    'feat.two_min_audits': '2-मिनट ऑडिट',
    'feat.two_min_desc': 'संरचित साप्ताहिक स्थिति प्रपत्र - स्कूल के कर्मचारियों द्वारा 2 मिनट के भीतर पूरा किया जा सकता है।',
    'feat.compliant': '% अनुपालन',
    'preview.asset_health': 'संपत्ति स्वास्थ्य',
    'preview.live_prediction': 'लाइव भविष्यवाणी इंजन',
    'preview.total_control': 'पूर्ण नियंत्रण.',
    'preview.bespoke_telemetry': 'बेस्पोक टेलीमेट्री.',
    'preview.risk_factor': 'जोखिम कारक',
    'preview.infra_zone': 'बुनियादी ढांचा क्षेत्र ए-12',
    'preview.remaining': 'शेष',
    'preview.status': 'स्थिति',
    'preview.active': 'सक्रिय',
    'preview.dispatch_team': 'टीम भेजें',
    'preview.priority_zone': 'प्राथमिकता क्षेत्र',
    'preview.model_school': 'मॉडल स्कूल #04',
    'preview.verified': 'सत्यापित',
    'preview.annual_audit': 'वार्षिक ऑडिट',
    'preview.safety_pass': 'सुरक्षा पास',
    'hiw.report': 'रिपोर्ट',
    'hiw.field_data': 'क्षेत्र_डेटा',
    'hiw.report_desc': 'स्कूल के कर्मचारी 2 मिनट से कम समय में संपत्ति की स्थिति पर संरचित साप्ताहिक रिपोर्ट जमा करते हैं।',
    'hiw.forecast': 'पूर्वानुमान',
    'hiw.ai_analysis': 'एआई_विश्लेषण',
    'hiw.forecast_desc': 'सक्षम के एआई मॉडल 30-60 दिनों की खिड़की के भीतर बुनियादी ढांचे की विफलताओं की भविष्यवाणी करने के लिए डेटा का विश्लेषण करते हैं।',
    'hiw.rank': 'रैंक',
    'hiw.impact_priority': 'प्रभाव_प्राथमिकता',
    'hiw.rank_desc': 'प्रणाली छात्र प्रभाव के आधार पर मरम्मत को प्राथमिकता देती है, लड़कियों के शौचालय जैसी महत्वपूर्ण सुविधाओं को पहले रैंकिंग देती है।',
    'hiw.resolve': 'समाधान करें',
    'hiw.audit_done': 'ऑडिट_पूर्ण',
    'hiw.resolve_desc': 'रखरखाव दल भेजे जाते हैं, और अंतिम समाधान को पहले/बाद के दस्तावेज़ीकरण के साथ सत्यापित किया जाता है।',
    'hiw.cycle': 'भविष्य कहनेवाला चक्र',
    'hiw.predicting_to': 'भविष्यवाणी करना',
    'hiw.protect_safety': 'सुरक्षा की रक्षा करें.',
    'hiw.desc': 'हमने प्रतिक्रियाशील मरम्मत से भविष्य कहनेवाला रखरखाव में संक्रमण किया, यह सुनिश्चित करते हुए कि स्कूल की संपत्ति हमेशा सुरक्षित रहे।',
    'testi.title_1': 'जिला अधिकारी',
    'testi.desc_1': 'डीईओ के लिए वास्तविक दुनिया के छात्र प्रभाव स्कोर के आधार पर प्राथमिकता वाली रखरखाव कतारों की निगरानी के लिए एक केंद्रीकृत डैशबोर्ड।',
    'testi.title_2': 'क्षेत्र रिपोर्टिंग',
    'testi.desc_2': 'स्कूल के कर्मचारियों के लिए 2 मिनट से कम समय में संरचनात्मक स्वास्थ्य जांच पूरी करने के लिए अनुकूलित मोबाइल फॉर्म।',
    'testi.title_3': 'ठेकेदार सिंक',
    'testi.desc_3': 'पहले/बाद के सत्यापन और जीपीएस-टैग किए गए रिज़ॉल्यूशन ऑडिट के साथ स्वचालित कार्य आदेश।',
    'testi.title_4': 'पूर्वानुमानित विश्लेषण',
    'testi.desc_4': 'एआई मॉडल 30-60 दिन पहले प्लंबिंग, इलेक्ट्रिकल और संरचनात्मक प्रणालियों के लिए विफलता खिड़कियों की भविष्यवाणी करते हैं।',
    'testi.built_for': 'हर के लिए बनाया गया',
    'testi.institution': 'संस्थान।',
    'dl.schools_monitored': 'निगरानी_किए_गए_स्कूल',
    'dl.terminal_ready': 'क्षेत्र टर्मिनल तैयार',
    'dl.title': 'ऑडिट ऐप.',
    'dl.subtitle': 'हर स्कूल में.',
    'dl.desc': 'एक संरचित ऑडिटिंग टूल के साथ स्कूल के कर्मचारियों को सशक्त बनाएं। रीयल-टाइम सिंक के साथ 2 मिनट से कम समय में साप्ताहिक स्थिति रिपोर्ट जमा करें।',
    'dl.download_on': 'यहाँ से डाउनलोड करें',
    'dl.get_it_on': 'यहाँ पर प्राप्त करें',
    'dl.scan_for': 'इसके लिए स्कैन करें',
    'dl.sync_active': 'ऑडिट_सिंक_सक्रिय',
    'foot.op_mode': 'परिचालन_मोड',
    'foot.predictive_live': 'भविष्य कहनेवाला_लाइव',
    'foot.uptime': 'अपटाइम_प्रोटोकॉल',
    'foot.node_status': 'नोड_स्थिति',
    'foot.gujarat_west': 'गुजरात_पश्चिम_01',
    'foot.api_core': 'एपीआई_कोर',
    'foot.v2_stable': 'v2.4.0_स्थिर',
    'foot.desc': 'संस्थागत बुनियादी ढांचे के लिए निश्चित भविष्य कहनेवाला रखरखाव इंजन। हर कक्षा के लिए डेटा-संचालित सुरक्षा।',
    'foot.useful_links': 'उपयोगी लिंक्स',
    'foot.about': 'हमारे बारे में',
    'foot.features': 'विशेषताएं',
    'foot.app_preview': 'ऐप पूर्वावलोकन',
    'foot.pricing': 'मूल्य निर्धारण',
    'foot.legal_support': 'कानूनी और सहायता',
    'foot.privacy': 'गोपनीयता नीति',
    'foot.terms': 'सेवा की शर्तें',
    'foot.system_status': 'सिस्टम स्थिति',
    'foot.contact': 'समर्थन से संपर्क करें',
    'foot.stay_updated': 'अपडेट रहें',
    'foot.stay_updated_desc': 'नवीनतम बुनियादी ढांचा अंतर्दृष्टि और सिस्टम अपडेट प्राप्त करें।',
    'foot.enter_email': 'ईमेल पता दर्ज करें',
    'foot.subscribe': 'अभी सदस्यता लें',
    'foot.made_in': 'भारत में ❤️ के साथ बनाया गया।',
    'foot.copyright': 'कॉपीराइट ©',
    'login.role_admin': 'सिस्टम व्यवस्थापक',
    'login.role_deo': 'जिला अधिकारी',
    'login.role_principal': 'स्कूल प्रिंसिपल',
    'login.role_contractor': 'ठेकेदार',
    'login.role_peon': 'स्कूल चपरासी',
    'login.predictive_engine': 'भविष्य कहनेवाला इंजन v3',
    'login.welcome': 'स्वागत है',
    'login.the_core': 'द कोर में।',
    'login.desc': 'सुरक्षित एक्सेस गेटवे। भविष्य कहनेवाला बुनियादी ढांचा डैशबोर्ड तक पहुंचने के लिए अपनी पहचान प्रमाणित करें।',
    'login.system_secure': 'सिस्टम सुरक्षित',
    'login.encrypted_conn': 'एन्क्रिप्टेड कनेक्शन',
    'login.system_operational': 'सिस्टम चालू है',
    'login.auth_title': 'प्रमाणित करें।',
    'login.auth_subtitle': 'पोर्टल तक पहुँचने के लिए क्रेडेंशियल दर्ज करें',
    'login.invalid_creds': 'अमान्य क्रेडेंशियल। कृपया पुनः प्रयास करें।',
    'login.email_label': 'पहचान / ईमेल पता',
    'login.password_label': 'सुरक्षित पासवर्ड',
    'login.authenticate_btn': 'प्रमाणित करें',
    'login.sandbox_identities': 'सैंडबॉक्स पहचान · पासवर्ड: password123',
    'login.need_access': 'बुनियादी ढांचे की पहुंच चाहिए? ',
    'login.request_profile': 'प्रोफ़ाइल का अनुरोध करें',
    'signup.role_peon': 'स्कूल चपरासी',
    'signup.role_principal': 'स्कूल प्रिंसिपल',
    'signup.role_deo': 'डीईओ',
    'signup.role_contractor': 'ठेकेदार',
    'signup.role_admin': 'व्यवस्थापक',
    'signup.predictive_engine': 'भविष्य कहनेवाला इंजन v3',
    'signup.build_the': 'बनाएं',
    'signup.infrastructure': 'बुनियादी ढांचा',
    'signup.of_tomorrow': 'कल का।',
    'signup.desc': '30,000+ स्कूलों को सुरक्षित करने वाले भविष्य कहनेवाला रखरखाव नेटवर्क से जुड़ें। होने से पहले विफलताओं को रोकें।',
    'signup.high_risk': 'उच्च जोखिम पाया गया',
    'signup.structural_block': 'संरचनात्मक ब्लॉक बी',
    'signup.system_operational': 'सिस्टम चालू है',
    'signup.init_title': 'आरंभ करें।',
    'signup.init_subtitle': 'अपनी क्लीयरेंस प्रोफ़ाइल सेट करें',
    'signup.password_mismatch': 'पासवर्ड मेल नहीं खाते',
    'signup.reg_failed': 'पंजीकरण विफल रहा। पुनः प्रयास करें।',
    'signup.select_access': 'एक्सेस स्तर (RBAC) चुनें',
    'signup.full_name': 'पूरा नाम',
    'signup.email': 'ईमेल पता',
    'signup.contact_number': 'संपर्क नंबर',
    'signup.district': 'जिला अधिकार क्षेत्र',
    'signup.school_id': 'कैनोनिकल स्कूल आईडी',
    'signup.password': 'सुरक्षित पासवर्ड',
    'signup.confirm_password': 'पासवर्ड की पुष्टि करें',
    'signup.authorize': 'क्लीयरेंस अधिकृत करें',
    'signup.already_have': 'पहले से ही क्लीयरेंस है? ',
    'signup.return_hub': 'हब पर लौटें',
    'peon.title': 'स्थिति ऑडिट फॉर्म (साप्ताहिक)',
    'peon.ref': 'संदर्भ',
    'peon.week': 'सप्ताह',
    'peon.instruction_title': 'स्कूल कर्मियों के लिए निर्देश',
    'peon.instruction_desc': 'कृपया प्रत्येक श्रेणी के लिए सटीक भौतिक मूल्यांकन प्रदान करें। प्राथमिकता के आधार पर रखरखाव आवंटन के लिए पहचाने जाने योग्य समस्याओं की स्पष्ट तस्वीर अपलोड करना अनिवार्य है।',
    'peon.cat_plumbing': 'नलसाजी (Plumbing)',
    'peon.cat_electrical': 'विद्युत (Electrical)',
    'peon.cat_structural': 'संरचनात्मक (Structural)',
    'peon.unit_assessment': 'इकाई मूल्यांकन',
    'peon.condition_state': 'स्थिति (1-5)',
    'peon.required': 'आवश्यक',
    'peon.score_1': 'बहुत अच्छा',
    'peon.score_2': 'अच्छा',
    'peon.score_3': 'ठीक है',
    'peon.score_4': 'खराब',
    'peon.score_5': 'गंभीर',
    'peon.deficiency_list': 'कमी चेकलिस्ट',
    'peon.toilet_1_0': 'सभी चालू',
    'peon.toilet_0_75': 'अधिकांश चालू',
    'peon.toilet_0_5': 'आंशिक रूप से चालू',
    'peon.toilet_0_25': 'कुछ चालू',
    'peon.toilet_0_0': 'कोई भी चालू नहीं',
    'peon.power_0': 'कोई बिजली कटौती नहीं',
    'peon.power_3': 'न्यूनतम',
    'peon.power_8': 'उल्लेखनीय',
    'peon.power_15': 'महत्वपूर्ण',
    'peon.power_25': 'गंभीर',
    'peon.crack_0': 'कोई दरार नहीं',
    'peon.crack_0_5': 'बालों जैसी दरारें',
    'peon.crack_2': 'मामूली',
    'peon.crack_6': 'मध्यम',
    'peon.crack_15': 'बड़ी',
    'peon.crack_25': 'गंभीर',
    'peon.flag_waterLeak': 'पानी का रिसाव',
    'peon.flag_brokenTap': 'टूटा हुआ नल',
    'peon.flag_cloggedDrain': 'जाम नाली',
    'peon.flag_tankOverflow': 'टंकी ओवरफ्लो',
    'peon.flag_lowWaterPressure': 'पानी का कम दबाव',
    'peon.flag_wallSeepage': 'दीवार में सीलन',
    'peon.flag_roofLeakFlag': 'छत टपकना',
    'peon.flag_brokenDoor': 'टूटा हुआ दरवाजा',
    'peon.flag_pestInfestation': 'कीट समस्याएँ',
    'peon.flag_issueFlag': 'अन्य समस्या',
    'peon.flag_wiringExposed': 'खुली वायरिंग',
    'peon.flag_brokenSwitch': 'टूटा हुआ स्विच',
    'peon.flag_burntSocket': 'जला हुआ सॉकेट',
    'peon.flag_flickeringLights': 'टिमटिमाती रोशनी',
    'peon.flag_panelDamage': 'पैनल क्षति',
    'peon.flag_highVoltage': 'वोल्टेज वृद्धि',
    'peon.flag_brokenWindow': 'टूटी हुई खिड़की',
    'peon.flag_paintPeeling': 'पेंट निकलना',
    'peon.flag_floorDamage': 'फर्श की दरारें',
    'peon.flag_ceilingHole': 'छत में छेद',
    'peon.observe': 'निरीक्षण करें और चुनें...',
    'peon.submit_report': 'ऑडिट रिपोर्ट जमा करें',
    'peon.photo_evidence': 'प्रमाण फोटोग्राफी',
    'peon.photo_success': 'छवि सफलतापूर्वक ली गई',
    'peon.photo_select': 'निरीक्षण फोटो का चयन करें',
    'peon.photo_format': 'JPG, PNG स्वीकृत (अधिकतम 5MB)',
    'ht.loading_chart': 'चार्ट लोड हो रहा है...',
    'ht.title': 'बुनियादी ढांचा स्वास्थ्य समयरेखा',
    'ht.subtitle': 'डोमेन भर में ऐतिहासिक स्थिति विश्लेषण',
    'ht.plumbing': 'नलसाजी',
    'ht.electrical': 'विद्युत',
    'ht.structural': 'संरचनात्मक',
    'ht.footer_text': 'उच्च मूल्य इष्टतम बुनियादी ढांचे की अखंडता का संकेत देते हैं (0-100 सूचकांक)',
    'deo.view_evidence': 'प्रमाण देखें',
    'nav.principal_dashboard': 'प्रधानाचार्य डैशबोर्ड',
    'nav.view_reports': 'रिपोर्ट देखें',
    'nav.predictive_queue': 'भविष्य कहनेवाला कतार',
    'nav.forwarded_reports': 'अग्रेषित रिपोर्ट',
    'nav.live_map': 'लाइव मानचित्र',
    'nav.command_center': 'कमांड सेंटर',
    'nav.field_console': 'फील्ड कंसोल',
    'nav.all_orders': 'सभी आदेश',
    'nav.admin_panel': 'एडमिन पैनल',
    'nav.audit_log': 'ऑडिट लॉग',
    'role.peon': 'चपरासी/चौकीदार',
    'role.principal': 'प्रधानाचार्य',
    'role.deo': 'DEO कमांड',
    'role.contractor': 'ठेकेदार',
    'role.admin': 'सिस्टम एडमिन',
    'role.school': 'विद्यालय',
    'fr.title': 'अग्रेषित स्कूल रिपोर्ट',
    'fr.subtitle': 'प्रधानाचार्यों द्वारा अग्रेषित बंडल · LR तात्कालिकता द्वारा रैंक किए गए',
    'fr.bundle': 'बंडल',
    'fr.bundles': 'बंडल',
    'fr.view_all': 'सभी देखें',
    'fr.loading': 'अग्रेषित बंडल लोड हो रहे हैं…',
    'fr.no_reports': 'अभी तक प्रधानाचार्यों द्वारा कोई रिपोर्ट अग्रेषित नहीं की गई है।',
    'fr.week_abbr': 'सप्ताह',
    'fr.30_day_fail': '30-दिन विफलता',
    'fr.worst': 'सबसे खराब',
    'fr.forwarded': 'अग्रेषित',
    'fr.lr_urgency': 'LR तात्कालिकता',
    'fr.pdf': 'पीडीएफ',
    'fr.assign': 'सौंपें',
    'fr.more_bundles': 'अधिक बंडल · सभी देखें',
    'nav.logout': 'लॉग आउट',
    'clv.photo_on_file': 'फ़ाइल में फ़ोटो',
    'clv.lr_urgency': 'LR तात्कालिकता',
    'clv.days_to_failure': 'विफलता तक के दिन',
    'clv.week': 'सप्ताह',
    'clv.weekly_bundle': 'साप्ताहिक बंडल',
    'clv.categories': 'श्रेणियां',
    'clv.category': 'श्रेणी',
    'clv.worst': 'सबसे खराब',
    'clv.submitted': 'जमा किया गया',
    'clv.lr_urgency_score': 'LR तात्कालिकता स्कोर',
    'clv.view_pdf': 'पीडीएफ देखें',
    'clv.sent_to_deo': 'DEO को भेजा गया',
    'clv.send_to_deo': 'DEO को भेजें',
    'clv.assign_contractor': 'ठेकेदार नियुक्त करें',
    'clv.lr_model_output': 'LR मॉडल आउटपुट (TS-PS3.csv प्रशिक्षित)',
    'clv.forwarded_to_deo_on': 'को DEO को अग्रेषित किया गया',
    'clv.loading_reports': 'रिपोर्ट लोड हो रही है...',
    'clv.access_restricted': 'पहुँच प्रतिबंधित',
    'clv.auth_required': 'इस दृश्य के लिए प्रधानाचार्य या DEO प्राधिकरण आवश्यक है।',
    'clv.account_unlinked': 'खाता असंबद्ध',
    'clv.no_school': 'आपका प्रधानाचार्य खाता किसी स्कूल से संबद्ध नहीं है.',
    'clv.deo_title': 'अग्रेषित साप्ताहिक रिपोर्ट',
    'clv.prin_title': 'साप्ताहिक स्थिति रिपोर्ट',
    'clv.deo_subtitle': 'प्रधानाचार्यों द्वारा अग्रेषित बंडल — LR तात्कालिकता द्वारा क्रमबद्ध, शीर्ष पर सबसे जरूरी',
    'clv.prin_subtitle': 'प्रति सप्ताह मूल्यांकन — प्रत्येक कार्ड LR मॉडल चलाता है और सभी 3 श्रेणियों को बंडल करता है',
    'clv.total_bundles': 'कुल साप्ताहिक बंडल',
    'clv.critical_urgency': 'गंभीर तात्कालिकता',
    'clv.predicted_fail': 'संभावित विफलता < 30 दिन',
    'clv.sent_to_deo_stat': 'DEO को भेजा गया',
    'clv.pending': 'लंबित',
    'clv.refine_view': 'दृश्य परिष्कृत करें:',
    'clv.any_urgency': 'कोई भी तात्कालिकता',
    'clv.all_bundles': 'सभी बंडल',
    'clv.awaiting_deo': 'DEO की प्रतीक्षा में',
    'clv.sent_filter': 'DEO को भेजा गया',
    'clv.bundles_sorted': 'बंडल · LR तात्कालिकता द्वारा क्रमबद्ध',
    'clv.lr_reports': 'साप्ताहिक रिपोर्ट (LR-प्राथमिकता)',
    'clv.one_card': 'प्रति सप्ताह एक कार्ड — शीर्ष पर सबसे जरूरी',
    'clv.no_reports': 'अभी तक कोई साप्ताहिक रिपोर्ट जमा नहीं की गई है।',
    'clv.no_match': 'कोई भी बंडल वर्तमान फ़िल्टर से मेल नहीं खाता।',
    'clv.forwarding': 'सप्ताह अग्रेषित किया जा रहा है'
  },
  gu: {
    'wo.title': 'ઇન્ફ્રાસ્ટ્રક્ચર ઓર્ડર',
    'wo.subtitle.contractor': 'કામગીરીના નિરાકરણ માટે ફાળવેલ કાર્યો',
    'wo.subtitle.deo': 'જિલ્લાવ્યાપી જાળવણી સોંપણીઓની દેખરેખ',
    'wo.auth_btn': 'નવો ઓર્ડર બનાવો',
    'wo.total': 'કુલ ઓર્ડર',
    'wo.active': 'સક્રિય ઓર્ડર',
    'wo.completed': 'પૂર્ણ થયેલ',
    'wo.sla': 'એસએલએ ભંગ',
    'wo.alert.title': 'એસએલએ પાલન ચેતવણી',
    'wo.alert.desc': 'અધિકૃત સમયમર્યાદા ઓળંગતા ઓર્ડર',
    'wo.tab.all': 'બધા',
    'wo.loading': 'ડેટા લોડ થઈ રહ્યો છે...',
    'wo.empty': 'કોઈ મેળ ખાતા વર્ક ઓર્ડર મળ્યા નથી.',
    'wo.th.type': 'પ્રકાર',
    'wo.th.location': 'સ્થાન',
    'wo.th.personnel': 'કર્મચારીઓ',
    'wo.th.deadline': 'અંતિમ મુદત',
    'wo.th.offset': 'વિલંબ',
    'wo.th.status': 'સ્થિતિ',
    'wo.th.actions': 'ક્રિયાઓ',
    'wo.ref': 'સંદર્ભ:',
    'wo.unknown_node': 'અજ્ઞાત સ્થાન',
    'wo.unassigned': 'સોંપેલ નથી',
    'wo.na': 'લાગુ પડતું નથી',
    'wo.breach_badge': 'એસએલએ ભંગ',
    'wo.days': 'દિવસો',
    'wo.btn.assign': 'સોંપો',
    'wo.btn.complete': 'પૂર્ણ કરો',
    'status.pending': 'બાકી',
    'status.assigned': 'સોંપાયેલ',
    'status.in_progress': 'પ્રગતિમાં છે',
    'status.completed': 'પૂર્ણ',
    'status.cancelled': 'રદ કરેલ',
    'wo.form.title': 'જાળવણી નિર્દેશ તૈયાર કરો',
    'wo.form.target_node': 'લક્ષ્ય ઇન્ફ્રાસ્ટ્રક્ચર નોડ',
    'wo.form.select_node': 'નોડ પસંદ કરો...',
    'wo.form.assigned_category': 'નિયુક્ત શ્રેણી',
    'wo.form.operational_priority': 'ઓપરેશનલ પ્રાથમિકતા',
    'wo.form.objective_desc': 'ઉદ્દેશ્ય વર્ણન',
    'wo.form.detailed_scope': 'કામનો વિગતવાર વ્યાપ...',
    'wo.form.designated_personnel': 'નિયુક્ત કર્મચારીઓ',
    'wo.form.unassigned': 'અનિયુક્ત',
    'wo.form.compliance_deadline': 'અનુપાલન અંતિમ તારીખ',
    'wo.form.discard': 'કાઢી નાખો',
    'wo.form.authorize': 'નિર્દેશ અધિકૃત કરો',
    'priority.critical': 'નિર્ણાયક',
    'priority.high': 'ઉચ્ચ',
    'priority.medium': 'મધ્યમ',
    'priority.low': 'નિમ્ન',
    'deo.title': 'વહીવટી દેખરેખ કેન્દ્ર',
    'deo.subtitle': 'જિલ્લા ઈન્ફ્રાસ્ટ્રક્ચર આરોગ્ય અને અનુમાનાત્મક જાળવણી વ્યવસ્થાપન',
    'deo.all_work_orders': 'બધા વર્ક ઓર્ડર',
    'deo.assessed_schools': 'આકારણી કરેલ શાળાઓ',
    'deo.critical_risk': 'ગંભીર જોખમ',
    'deo.high_priority': 'ઉચ્ચ પ્રાથમિકતા',
    'deo.trending': 'ટ્રેન્ડિંગ',
    'deo.avg_survival': 'સરેરાશ આયુષ્ય',
    'deo.days': 'દિવસો',
    'deo.risk_queue_title': 'જોખમ સંચાલન કતાર',
    'deo.risk_queue_subtitle': 'ઈન્ફ્રાસ્ટ્રક્ચર નોડ્સનું રીઅલ-ટાઇમ પ્રિડિક્ટિવ વિશ્લેષણ',
    'deo.risk_queue_tab': 'જોખમ કતાર',
    'deo.gps_mismatches_tab': 'જીપીએસ વિસંગતતાઓ',
    'deo.filter_placeholder': 'જિલ્લો શોધો...',
    'deo.loading_scans': 'જોખમ સ્કેન લોડ થઈ રહ્યું છે...',
    'deo.no_critical_nodes': 'વર્તમાન રજિસ્ટ્રી સ્કેનમાં કોઈ ગંભીર જોખમ નોડ મળ્યા નથી.',
    'deo.score': 'સ્કોર',
    'deo.failure_horizon': 'નિષ્ફળતા ક્ષિતિજ',
    'deo.student_impact': 'વિદ્યાર્થી પ્રભાવ',
    'deo.pts': 'પોઇન્ટ્સ',
    'deo.resolve': 'ઉકેલ લાવો',
    'deo.no_mismatches': 'કોઈ સ્થાન વિસંગતતા મળી નથી',
    'deo.th.protocol': 'પ્રોટોકોલ',
    'deo.th.contractor': 'કોન્ટ્રાક્ટર / સાઇટ',
    'deo.th.coordinates': 'કોઓર્ડિનેટ્સ',
    'deo.th.alert': 'ચેતવણી',
    'deo.th.variance': 'વિવિધતા',
    'deo.verify_proof': 'પુરાવા ચકાસો',
    'deo.unknown_school': 'અજ્ઞાત શાળા',
    'deo.verified_by': 'દ્વારા ચકાસાયેલ',
    'deo.staff': 'સ્ટાફ',
    'deo.submitted': 'સબમિટ કરેલ',
    'deo.registry': 'રજિસ્ટ્રી',
    'deo.location_variance': 'સ્થાન વિસંગતતા',
    'deo.breach_detected': 'ભંગ જોવા મળ્યો',
    'deo.outside_perimeter': 'સુરક્ષા પરિમિતિની બહાર',
    'deo.last_sync': 'છેલ્લું સિંક્રનાઇઝેશન',
    'deo.security_registry_operational': 'સુરક્ષા રજિસ્ટ્રી કાર્યરત છે',
    'sv.analyzing': 'પ્રોફાઇલનું વિશ્લેષણ કરી રહ્યા છીએ...',
    'sv.access_restricted': 'પ્રવેશ પ્રતિબંધિત',
    'sv.admin_credentials_req': 'આ પ્રોફાઇલ જોવા માટે વહીવટી ઓળખપત્રો જરૂરી છે.',
    'sv.unspecified_region': 'અનિર્દિષ્ટ પ્રદેશ',
    'sv.age': 'ઉંમર',
    'sv.registry': 'રજિસ્ટ્રી',
    'sv.generic_node': 'પ્રિન્સિપલ ડેશબોર્ડ',
    'sv.admin_oversight': 'વહીવટી દેખરેખ કેન્દ્ર',
    'sv.submit_audit': 'ઓડિટ સબમિટ કરો',
    'sv.resource_registry': 'સંસાધન રજિસ્ટ્રી',
    'sv.infra_health': 'ઈન્ફ્રાસ્ટ્રક્ચર આરોગ્ય',
    'sv.global_condition': 'વૈશ્વિક સ્થિતિ અનુક્રમણિકા',
    'sv.pending_audits': 'બાકી ઓડિટ',
    'sv.due_this_month': 'આ મહિને બાકી',
    'sv.critical_risks': 'ગંભીર જોખમો',
    'sv.high_risk_vectors': 'ઉચ્ચ જોખમ વેક્ટર્સ',
    'sv.audit_history': 'ઓડિટ ઇતિહાસ',
    'sv.registry_volume': 'રજિસ્ટ્રી વોલ્યુમ',
    'sv.risk_spectrum': 'જોખમ સ્પેક્ટ્રમ',
    'sv.domain_specific': 'ડોમેન-વિશિષ્ટ મૂલ્યાંકન',
    'sv.infra_survival': 'ઈન્ફ્રાસ્ટ્રક્ચર જીવન વિશ્લેષણ',
    'sv.predictive_engine': 'અનુમાનાત્મક એનાલિટિક્સ એન્જિન',
    'sv.failure_horizon': 'નિષ્ફળતા ક્ષિતિજ',
    'sv.trend_vector': 'વલણ અને વેક્ટર',
    'sv.critical_worst': 'ગંભીર',
    'sv.none': 'કોઈ નહીં',
    'sv.insufficient_data': 'અનુમાનાત્મક જીવન વિશ્લેષણ માટે અપૂરતો ઓડિટ ડેટા.',
    'gs.cap_1_title': 'માળખાકીય આગાહી કરનાર',
    'gs.cap_1_desc': 'કોંક્રિટ અધોગતિ અને સ્લેબ તણાવની AI-સંચાલિત શોધ.',
    'gs.cap_2_title': 'અસર પ્રાથમિકતા',
    'gs.cap_2_desc': 'વિદ્યાર્થીઓના ઉપયોગ અને સુવિધાના પ્રકાર પર આધારિત સ્વચાલિત રેન્કિંગ.',
    'gs.cap_3_title': '60-દિવસની ક્ષિતિજ',
    'gs.cap_3_desc': 'પ્લમ્બિંગ અને ઇલેક્ટ્રિકલ ગ્રીડ માટે નિષ્ફળતા વિંડોની આગાહીઓ.',
    'gs.cap_4_title': '2-મિનિટ સ્ટાફ ઓડિટ',
    'gs.cap_4_desc': 'શૂન્ય મુક્ત-લખાણ ઘર્ષણ સાથે સંરચિત સાપ્તાહિક આરોગ્ય અહેવાલો.',
    'gs.cap_5_title': 'જીપીએસ ચકાસણી',
    'gs.cap_5_desc': 'જીઓ-ટેગ કરેલા દસ્તાવેજો સાથે કોન્ટ્રાક્ટર રિઝોલ્યુશન ઓડિટ.',
    'gs.cap_6_title': 'એસએલએ ટ્રેકિંગ',
    'gs.cap_6_desc': 'ફરિયાદ નિરાકરણ સમયરેખાનું વાસ્તવિક સમયનું નિરીક્ષણ.',
    'gs.cap_7_title': 'ડીઇઓ ડેશબોર્ડ',
    'gs.cap_7_desc': 'કેન્દ્રિય જિલ્લાવ્યાપી સંપત્તિ આરોગ્ય વિઝ્યુલાઇઝેશન.',
    'gs.cap_8_title': 'અનુમાનાત્મક જોખમ',
    'gs.cap_8_desc': 'મકાનની ઉંમર અને હવામાન ડેટાનો ઉપયોગ કરીને ઉચ્ચ-જોખમવાળા વિસ્તારોને ઓળખો.',
    'gs.live_intelligence': 'લાઇવ ઇન્ટેલિજન્સ',
    'gs.engine': 'એન્જિન',
    'gs.capabilities': 'ક્ષમતાઓ.',
    'gs.map_filters': 'નકશા ફિલ્ટર્સ',
    'gs.show_all_sites': 'તમામ સાઇટ્સ બતાવો',
    'gs.critical_only': '🔴 ફક્ત નિર્ણાયક',
    'gs.recenter': 'મારા સ્થાન પર ફરીથી કેન્દ્રિત કરો',
    'gs.title': 'ઇન્ફ્રાસ્ટ્રક્ચર મેપિંગ ગ્રીડ',
    'gs.subtitle': 'પ્રદેશોમાં માળખાકીય જોખમ આધાર રેખાનું જીઓસ્પેશિયલ મોનિટરિંગ',
    'gs.all_districts': 'તમામ જિલ્લાઓ',
    'gs.update': 'અપડેટ કરો',
    'gs.id_nodes': 'ઓળખ નોડ્સ',
    'gs.critical_desig': 'નિર્ણાયક હોદ્દો',
    'gs.stable_baseline': 'સ્થિર બેઝલાઇન',
    'gs.nav_target': 'લક્ષ્ય તરફ નેવિગેટ કરી રહ્યું છે',
    'gs.distance': 'અંતર',
    'gs.km': 'કિમી',
    'gs.est_eta': 'અંદાજિત ઇટીએ',
    'gs.min': 'મિનિટ',
    'gs.cancel_nav': 'નેવિગેશન રદ કરો',
    'gs.syncing_gps': 'GPS નોડ્સ સિંક થઈ રહ્યાં છે...',
    'gs.designation': 'હોદ્દો',
    'gs.routing': 'રૂટીંગ...',
    'gs.get_directions': 'દિશાઓ મેળવો',
    'gs.view_profile': 'સંપૂર્ણ પ્રોફાઇલ જુઓ',
    'gs.user_node': 'વપરાશકર્તા નોડ',
    'gs.gps_active': 'ઓપરેશનલ જીપીએસ સક્રિય',
    'gs.access_denied': 'ઍક્સેસ નકારવામાં આવી.',
    'gs.alert_location': 'કૃપા કરીને દિશાઓ મેળવવા માટે સ્થાન ઍક્સેસની મંજૂરી આપો.',
    'gs.alert_route_fail': 'રૂટની ગણતરી કરી શકાઈ નથી.',
    'gs.alert_fetch_fail': 'રૂટ લાવવામાં નિષ્ફળ.',
    'alv.access_denied': 'પ્રવેશ નકારાયો',
    'alv.title': 'સિસ્ટમ ઑડિટ લૉગ',
    'alv.subtitle': 'તમામ પ્લેટફોર્મ ક્રિયાઓનો અપરિવર્તનશીલ રેકોર્ડ',
    'alv.actor_role': 'અભિનેતાની ભૂમિકા',
    'alv.all_roles': 'તમામ ભૂમિકાઓ',
    'alv.action_sig': 'ક્રિયા સહી',
    'alv.filter_action': 'ઇવેન્ટના નામ દ્વારા ફિલ્ટર કરો...',
    'alv.window_start': 'લૉગ વિન્ડો પ્રારંભ',
    'alv.window_end': 'લૉગ વિન્ડો અંત',
    'alv.apply_filters': 'ફિલ્ટર્સ લાગુ કરો',
    'alv.th_timestamp': 'ટાઇમસ્ટેમ્પ',
    'alv.th_actor': 'અભિનેતા',
    'alv.th_role': 'ભૂમિકા',
    'alv.th_action': 'ક્રિયા સહી',
    'alv.th_target': 'સંસાધન લક્ષ્ય',
    'alv.th_details': 'વિગતો',
    'alv.syncing': 'લોગ્સ સિંક્રનાઇઝ થઈ રહ્યાં છે...',
    'alv.no_events': 'અપરિવર્તનશીલ રજિસ્ટ્રીમાં કોઈ મેળ ખાતી ઑડિટ ઇવેન્ટ્સ મળી નથી.',
    'alv.unknown_actor': 'અજ્ઞાત અભિનેતા',
    'alv.unknown_role': 'અજ્ઞાત',
    'alv.general_system': 'સામાન્ય સિસ્ટમ',
    'alv.payload': 'પેલોડ',
    'alv.extracted_metadata': 'એક્સટ્રેક્ટેડ મેટાડેટા',
    'alv.registry_page': 'રજિસ્ટ્રી પૃષ્ઠ',
    'alv.events': 'ઇવેન્ટ્સ',
    'nav.features': 'લક્ષણો',
    'nav.how_it_works': 'તે કેવી રીતે કામ કરે છે',
    'nav.app_preview': 'એપ્લિકેશન પૂર્વાવલોકન',
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.login': 'લોગિન',
    'hero.scan': 'માળખાકીય_સ્કેન',
    'hero.health_index': 'આરોગ્ય અનુક્રમણિકા',
    'hero.high_risk': 'ઉચ્ચ જોખમ',
    'hero.prediction_engine': 'અનુમાન એન્જિન',
    'hero.forecast_horizon': 'આગાહી ક્ષિતિજ',
    'hero.priority_active': 'પ્રાથમિકતા_સક્રિય',
    'hero.ranked_impact': 'વિદ્યાર્થીઓની અસર માટે # 1 ક્રમાંકિત',
    'hero.audit_ready': 'ઓડિટ તૈયાર',
    'hero.secure_core': 'સુરક્ષિત_કોર_સક્રિય',
    'hero.built_to': 'માટે બનાવેલ છે',
    'hero.typewriter_1': 'આગાહી.',
    'hero.typewriter_2': 'સમારકામ.',
    'hero.typewriter_3': 'સુરક્ષિત.',
    'hero.typewriter_4': 'જાળવણી.',
    'hero.description': '30,000+ શાળાઓ માટે એઆઈ-સંચાલિત ઈન્ફ્રાસ્ટ્રક્ચર ઇન્ટેલિજન્સ. સ્વયંસંચાલિત પ્રભાવ રેન્કિંગ સાથે 60 દિવસ આગળ નિષ્ફળતા શોધો.',
    'hero.enter_portal': 'પોર્ટલ દાખલ કરો',
    'hero.view_logs': 'લૉગ્સ જુઓ',
    'feat.infra_intel': 'ઇન્ફ્રાસ્ટ્રક્ચર ઇન્ટેલિજન્સ',
    'feat.predictive_core': 'અનુમાનાત્મક કોર.',
    'feat.structural_precision': 'માળખાકીય ચોકસાઇ.',
    'feat.multi_factor': 'મલ્ટી-ફેક્ટર આગાહી',
    'feat.multi_factor_desc': 'મકાનની ઉંમર, સામગ્રી અને હવામાન ઝોન ડેટાનો ઉપયોગ કરીને 30,000+ ઇમારતો માટે નિષ્ફળતાની વિંડોઝની આગાહી કરો.',
    'feat.structural': 'માળખાકીય',
    'feat.plumbing': 'પ્લમ્બિંગ',
    'feat.electrical': 'ઇલેક્ટ્રિકલ',
    'feat.impact_bias': 'અસર પૂર્વગ્રહ કતાર',
    'feat.impact_desc': 'સ્વચાલિત રેન્કિંગ સિસ્ટમ: કન્યા શાળાના શૌચાલય સમારકામ તિરાડ સ્ટોરેજ રૂમની દિવાલોથી ઉપર છે.',
    'feat.two_min_audits': '2-મિનિટ ઓડિટ્સ',
    'feat.two_min_desc': 'સ્ટ્રક્ચર્ડ સાપ્તાહિક શરત ફોર્મ્સ - શાળાના કર્મચારીઓ દ્વારા 2 મિનિટની અંદર પૂર્ણ કરી શકાય છે.',
    'feat.compliant': '% સુસંગત',
    'preview.asset_health': 'સંપત્તિ આરોગ્ય',
    'preview.live_prediction': 'જીવંત આગાહી એન્જિન',
    'preview.total_control': 'સંપૂર્ણ નિયંત્રણ.',
    'preview.bespoke_telemetry': 'બેસ્પોક ટેલિમેટ્રી.',
    'preview.risk_factor': 'જોખમ પરિબળ',
    'preview.infra_zone': 'ઇન્ફ્રાસ્ટ્રક્ચર ઝોન A-12',
    'preview.remaining': 'બાકી',
    'preview.status': 'સ્થિતિ',
    'preview.active': 'સક્રિય',
    'preview.dispatch_team': 'ટીમ રવાના કરો',
    'preview.priority_zone': 'પ્રાધાન્યતા ઝોન',
    'preview.model_school': 'મોડેલ સ્કૂલ #04',
    'preview.verified': 'ચકાસાયેલ',
    'preview.annual_audit': 'વાર્ષિક ઓડિટ',
    'preview.safety_pass': 'સલામતી પાસ',
    'hiw.report': 'અહેવાલ',
    'hiw.field_data': 'ફિલ્ડ_ડેટા',
    'hiw.report_desc': 'શાળાના કર્મચારીઓ 2 મિનિટથી ઓછા સમયમાં સંપત્તિની સ્થિતિ પર માળખાગત સાપ્તાહિક અહેવાલો સબમિટ કરે છે.',
    'hiw.forecast': 'આગાહી',
    'hiw.ai_analysis': 'એઆઈ_વિશ્લેષણ',
    'hiw.forecast_desc': 'સક્ષમના એઆઈ મોડલ્સ 30-60 દિવસની વિંડોમાં ઈન્ફ્રાસ્ટ્રક્ચર નિષ્ફળતાની આગાહી કરવા માટે ડેટાનું વિશ્લેષણ કરે છે.',
    'hiw.rank': 'રેન્ક',
    'hiw.impact_priority': 'અસર_પ્રાથમિકતા',
    'hiw.rank_desc': 'સિસ્ટમ વિદ્યાર્થીઓની અસરના આધારે સમારકામને પ્રાથમિકતા આપે છે, કન્યાઓના શૌચાલય જેવી જટિલ સુવિધાઓને પ્રથમ ક્રમાંક આપે છે.',
    'hiw.resolve': 'ઉકેલો',
    'hiw.audit_done': 'ઓડિટ_પૂર્ણ',
    'hiw.resolve_desc': 'જાળવણી ટીમો મોકલવામાં આવે છે, અને અંતિમ ઠરાવ પહેલાં/પછીના દસ્તાવેજીકરણ સાથે ચકાસવામાં આવે છે.',
    'hiw.cycle': 'અનુમાનાત્મક ચક્ર',
    'hiw.predicting_to': 'આગાહી કરવી',
    'hiw.protect_safety': 'સલામતીનું રક્ષણ કરો.',
    'hiw.desc': 'અમે રિએક્ટિવ સમારકામથી આગાહી જાળવણી તરફ સંક્રમણ કર્યું છે, ખાતરી કરો કે શાળાની સંપત્તિ હંમેશા સુરક્ષિત છે.',
    'testi.title_1': 'જિલ્લા અધિકારીઓ',
    'testi.desc_1': 'ડીઇઓ માટે વાસ્તવિક દુનિયાના વિદ્યાર્થી પ્રભાવ સ્કોર્સના આધારે પ્રાથમિક જાળવણી કતારો પર નજર રાખવા માટે કેન્દ્રિય ડેશબોર્ડ.',
    'testi.title_2': 'ક્ષેત્ર રિપોર્ટિંગ',
    'testi.desc_2': 'શાળાના કર્મચારીઓ માટે 2 મિનિટથી ઓછા સમયમાં માળખાકીય આરોગ્ય તપાસ પૂર્ણ કરવા માટે ઑપ્ટિમાઇઝ કરેલ મોબાઇલ ફોર્મ્સ.',
    'testi.title_3': 'કોન્ટ્રાક્ટર સિંક',
    'testi.desc_3': 'પહેલાં/પછીના ચકાસણી અને જીપીએસ-ટેગ કરેલા ઠરાવ ઓડિટ્સ સાથે સ્વચાલિત કાર્ય ઓર્ડર.',
    'testi.title_4': 'અનુમાનિત વિશ્લેષણ',
    'testi.desc_4': 'એઆઈ મોડલ્સ 30-60 દિવસ અગાઉથી પ્લમ્બિંગ, ઇલેક્ટ્રિકલ અને સ્ટ્રક્ચરલ સિસ્ટમ્સ માટે નિષ્ફળતાની વિંડોઝની આગાહી કરે છે.',
    'testi.built_for': 'દરેક માટે બનાવેલ છે',
    'testi.institution': 'સંસ્થા.',
    'dl.schools_monitored': 'નિરીક્ષણ_કરાયેલ_શાળાઓ',
    'dl.terminal_ready': 'ફિલ્ડ ટર્મિનલ તૈયાર છે',
    'dl.title': 'ઓડિટ એપ.',
    'dl.subtitle': 'દરેક શાળામાં.',
    'dl.desc': 'એક સંરચિત ઓડિટીંગ સાધન સાથે શાળાના કર્મચારીઓને સશક્ત બનાવો. રીયલ-ટાઇમ સમન્વયન સાથે 2 મિનિટથી ઓછા સમયમાં સાપ્તાહિક સ્થિતિ અહેવાલો સબમિટ કરો.',
    'dl.download_on': 'પર ડાઉનલોડ કરો',
    'dl.get_it_on': 'પર મેળવો',
    'dl.scan_for': 'આના માટે સ્કેન કરો',
    'dl.sync_active': 'ઓડિટ_સમન્વયન_સક્રિય',
    'foot.op_mode': 'ઓપરેશનલ_મોડ',
    'foot.predictive_live': 'અનુમાનિત_લાઇવ',
    'foot.uptime': 'અપટાઇમ_પ્રોટોકોલ',
    'foot.node_status': 'નોડ_સ્થિતિ',
    'foot.gujarat_west': 'ગુજરાત_પશ્ચિમ_01',
    'foot.api_core': 'API_કોર',
    'foot.v2_stable': 'v2.4.0_સ્થિર',
    'foot.desc': 'સંસ્થાકીય ઈન્ફ્રાસ્ટ્રક્ચર માટે નિર્ણાયક અનુમાનાત્મક જાળવણી એન્જિન. દરેક વર્ગખંડ માટે ડેટા આધારિત સુરક્ષા.',
    'foot.useful_links': 'ઉપયોગી કડીઓ',
    'foot.about': 'અમારા વિશે',
    'foot.features': 'વિશેષતાઓ',
    'foot.app_preview': 'એપ્લિકેશન પૂર્વાવલોકન',
    'foot.pricing': 'કિંમત નિર્ધારણ',
    'foot.legal_support': 'કાનૂની અને આધાર',
    'foot.privacy': 'ગોપનીયતા નીતિ',
    'foot.terms': 'સેવાની શરતો',
    'foot.system_status': 'સિસ્ટમ સ્થિતિ',
    'foot.contact': 'આધાર સંપર્ક કરો',
    'foot.stay_updated': 'અપડેટ રહો',
    'foot.stay_updated_desc': 'નવીનતમ માળખાગત આંતરદૃષ્ટિ અને સિસ્ટમ અપડેટ્સ મેળવો.',
    'foot.enter_email': 'ઇમેઇલ સરનામું દાખલ કરો',
    'foot.subscribe': 'હવે સબ્સ્ક્રાઇબ કરો',
    'foot.made_in': 'ભારતમાં ❤️ સાથે બનાવેલ છે.',
    'foot.copyright': 'કોપીરાઈટ ©',
    'login.role_admin': 'સિસ્ટમ એડમિન',
    'login.role_deo': 'જિલ્લા અધિકારી',
    'login.role_principal': 'શાળા આચાર્ય',
    'login.role_contractor': 'કોન્ટ્રાક્ટર',
    'login.role_peon': 'શાળા પટાવાળા',
    'login.predictive_engine': 'અનુમાનિત એન્જિન v3',
    'login.welcome': 'સ્વાગત છે',
    'login.the_core': 'ધ કોરમાં.',
    'login.desc': 'સુરક્ષિત ઍક્સેસ ગેટવે. અનુમાનિત ઇન્ફ્રાસ્ટ્રક્ચર ડેશબોર્ડને ઍક્સેસ કરવા માટે તમારી ઓળખને પ્રમાણિત કરો.',
    'login.system_secure': 'સિસ્ટમ સુરક્ષિત',
    'login.encrypted_conn': 'એન્ક્રિપ્ટેડ કનેક્શન',
    'login.system_operational': 'સિસ્ટમ ઓપરેશનલ છે',
    'login.auth_title': 'પ્રમાણિત કરો.',
    'login.auth_subtitle': 'પોર્ટલ ઍક્સેસ કરવા માટે ઓળખપત્રો દાખલ કરો',
    'login.invalid_creds': 'અમાન્ય ઓળખપત્રો. કૃપા કરીને ફરી પ્રયાસ કરો.',
    'login.email_label': 'ઓળખ / ઇમેઇલ સરનામું',
    'login.password_label': 'સુરક્ષિત પાસવર્ડ',
    'login.authenticate_btn': 'પ્રમાણિત કરો',
    'login.sandbox_identities': 'સેન્ડબોક્સ ઓળખ · પાસવર્ડ: password123',
    'login.need_access': 'ઇન્ફ્રાસ્ટ્રક્ચર ઍક્સેસની જરૂર છે? ',
    'login.request_profile': 'પ્રોફાઇલની વિનંતી કરો',
    'signup.role_peon': 'શાળા પટાવાળા',
    'signup.role_principal': 'શાળા આચાર્ય',
    'signup.role_deo': 'DEO',
    'signup.role_contractor': 'કોન્ટ્રાક્ટર',
    'signup.role_admin': 'એડમિન',
    'signup.predictive_engine': 'અનુમાનિત એન્જિન v3',
    'signup.build_the': 'બનાવો',
    'signup.infrastructure': 'ઇન્ફ્રાસ્ટ્રક્ચર',
    'signup.of_tomorrow': 'આવતીકાલનું.',
    'signup.desc': '30,000+ શાળાઓને સુરક્ષિત કરતા અનુમાનિત જાળવણી નેટવર્કમાં જોડાઓ. નિષ્ફળતાઓ થાય તે પહેલાં અટકાવો.',
    'signup.high_risk': 'ઉચ્ચ જોખમ મળ્યું',
    'signup.structural_block': 'સ્ટ્રક્ચરલ બ્લોક બી',
    'signup.system_operational': 'સિસ્ટમ ઓપરેશનલ છે',
    'signup.init_title': 'પ્રારંભ કરો.',
    'signup.init_subtitle': 'તમારી ક્લિયરન્સ પ્રોફાઇલ સેટ કરો',
    'signup.password_mismatch': 'પાસવર્ડ મેળ ખાતા નથી',
    'signup.reg_failed': 'નોંધણી નિષ્ફળ. ફરીથી પ્રયાસ કરો.',
    'signup.select_access': 'ઍક્સેસ સ્તર પસંદ કરો (RBAC)',
    'signup.full_name': 'પૂરું નામ',
    'signup.email': 'ઇમેઇલ સરનામું',
    'signup.contact_number': 'સંપર્ક નંબર',
    'signup.district': 'જિલ્લા અધિકારક્ષેત્ર',
    'signup.school_id': 'કેનોનિકલ શાળા ID',
    'signup.password': 'સુરક્ષિત પાસવર્ડ',
    'signup.confirm_password': 'પાસવર્ડની પુષ્ટિ કરો',
    'signup.authorize': 'ક્લિયરન્સ અધિકૃત કરો',
    'signup.already_have': 'પહેલેથી જ ક્લિયરન્સ છે? ',
    'signup.return_hub': 'હબ પર પાછા ફરો',
    'peon.title': 'સ્થિતિ ઑડિટ ફોર્મ (સાપ્તાહિક)',
    'peon.ref': 'સંદર્ભ',
    'peon.week': 'સપ્તાહ',
    'peon.instruction_title': 'શાળા કર્મચારીઓ માટે સૂચના',
    'peon.instruction_desc': 'કૃપા કરીને દરેક શ્રેણી માટે સચોટ ભૌતિક મૂલ્યાંકન પ્રદાન કરો. અગ્રતા જાળવણી ફાળવણી માટે ઓળખી શકાય તેવી સમસ્યાઓનો સ્પષ્ટ ફોટો અપલોડ કરવો ફરજિયાત છે.',
    'peon.cat_plumbing': 'પ્લમ્બિંગ (Plumbing)',
    'peon.cat_electrical': 'વિદ્યુત (Electrical)',
    'peon.cat_structural': 'માળખાકીય (Structural)',
    'peon.unit_assessment': 'એકમ મૂલ્યાંકન',
    'peon.condition_state': 'સ્થિતિ (1-5)',
    'peon.required': 'જરૂરી',
    'peon.score_1': 'ઉત્તમ',
    'peon.score_2': 'સારું',
    'peon.score_3': 'ઠીક',
    'peon.score_4': 'ખરાબ',
    'peon.score_5': 'ગંભીર',
    'peon.deficiency_list': 'ક્ષતિ ચેકલિસ્ટ',
    'peon.toilet_1_0': 'બધા કાર્યરત',
    'peon.toilet_0_75': 'મોટાભાગના કાર્યરત',
    'peon.toilet_0_5': 'આંશિક કાર્યરત',
    'peon.toilet_0_25': 'થોડા કાર્યરત',
    'peon.toilet_0_0': 'કોઈ કાર્યરત નથી',
    'peon.power_0': 'કોઈ પાવર આઉટેજ નથી',
    'peon.power_3': 'ન્યૂનતમ',
    'peon.power_8': 'નોંધપાત્ર',
    'peon.power_15': 'મહત્વપૂર્ણ',
    'peon.power_25': 'ગંભીર',
    'peon.crack_0': 'કોઈ તિરાડો નથી',
    'peon.crack_0_5': 'ઝીણી તિરાડો',
    'peon.crack_2': 'નાની',
    'peon.crack_6': 'મધ્યમ',
    'peon.crack_15': 'મોટી',
    'peon.crack_25': 'તીવ્ર',
    'peon.flag_waterLeak': 'પાણીનું લીકેજ',
    'peon.flag_brokenTap': 'તૂટેલો નળ',
    'peon.flag_cloggedDrain': 'જામ ડ્રેઇન',
    'peon.flag_tankOverflow': 'ટાંકી ઓવરફ્લો',
    'peon.flag_lowWaterPressure': 'પાણીનું ઓછું દબાણ',
    'peon.flag_wallSeepage': 'દીવાલ સીપેજ',
    'peon.flag_roofLeakFlag': 'છત લીક',
    'peon.flag_brokenDoor': 'તૂટેલો દરવાજો',
    'peon.flag_pestInfestation': 'જીવાતની સમસ્યાઓ',
    'peon.flag_issueFlag': 'અન્ય સમસ્યા',
    'peon.flag_wiringExposed': 'ખુલ્લું વાયરિંગ',
    'peon.flag_brokenSwitch': 'તૂટેલી સ્વીચ',
    'peon.flag_burntSocket': 'બળેલી સોકેટ',
    'peon.flag_flickeringLights': 'ઝબકતી લાઈટો',
    'peon.flag_panelDamage': 'પેનલનું નુકસાન',
    'peon.flag_highVoltage': 'વોલ્ટેજ વધારો',
    'peon.flag_brokenWindow': 'તૂટેલી બારી',
    'peon.flag_paintPeeling': 'રંગ ઉખડવો',
    'peon.flag_floorDamage': 'ફ્લોર તિરાડો',
    'peon.flag_ceilingHole': 'છતમાં કાણું',
    'peon.observe': 'નિરીક્ષણ કરો અને પસંદ કરો...',
    'peon.submit_report': 'ઑડિટ રિપોર્ટ સબમિટ કરો',
    'peon.photo_evidence': 'પુરાવા ફોટોગ્રાફી',
    'peon.photo_success': 'છબી સફળતાપૂર્વક લેવામાં આવી',
    'peon.photo_select': 'નિરીક્ષણ ફોટો પસંદ કરો',
    'peon.photo_format': 'JPG, PNG મંજૂર (મહત્તમ 5MB)',
    'ht.loading_chart': 'ચાર્ટ લોડ થઈ રહ્યો છે...',
    'ht.title': 'ઈન્ફ્રાસ્ટ્રક્ચર આરોગ્ય સમયરેખા',
    'ht.subtitle': 'ડોમેનભરમાં ઐતિહાસિક સ્થિતિ વિશ્લેષણ',
    'ht.plumbing': 'પ્લમ્બિંગ',
    'ht.electrical': 'ઇલેક્ટ્રિકલ',
    'ht.structural': 'માળખાકીય',
    'ht.footer_text': 'ઉચ્ચ મૂલ્યો શ્રેષ્ઠ ઇન્ફ્રાસ્ટ્રક્ચર અખંડિતતા દર્શાવે છે (0-100 અનુક્રમણિકા)',
    'deo.view_evidence': 'પુરાવા જુઓ',
    'nav.principal_dashboard': 'પ્રિન્સિપાલ ડેશબોર્ડ',
    'nav.view_reports': 'રિપોર્ટ્સ જુઓ',
    'nav.predictive_queue': 'અનુમાનાત્મક કતાર',
    'nav.forwarded_reports': 'ફોરવર્ડ કરેલા રિપોર્ટ્સ',
    'nav.live_map': 'જીવંત નકશો',
    'nav.command_center': 'કમાન્ડ સેન્ટર',
    'nav.field_console': 'ફિલ્ડ કન્સોલ',
    'nav.all_orders': 'બધા ઓર્ડર્સ',
    'nav.admin_panel': 'એડમિન પેનલ',
    'nav.audit_log': 'ઓડિટ લોગ',
    'role.peon': 'પટાવાળો/ચોકીદાર',
    'role.principal': 'આચાર્ય',
    'role.deo': 'DEO કમાન્ડ',
    'role.contractor': 'કોન્ટ્રાક્ટર',
    'role.admin': 'સિસ્ટમ એડમિન',
    'role.school': 'શાળા',
    'fr.title': 'ફોરવર્ડ કરેલ શાળા અહેવાલો',
    'fr.subtitle': 'પ્રિન્સિપાલ દ્વારા ફોરવર્ડ કરાયેલા બંડલ · LR તાકીદ દ્વારા ક્રમાંકિત',
    'fr.bundle': 'બંડલ',
    'fr.bundles': 'બંડલ્સ',
    'fr.view_all': 'બધા જુઓ',
    'fr.loading': 'ફોરવર્ડ કરાયેલ બંડલ લોડ કરી રહ્યાં છીએ…',
    'fr.no_reports': 'હજુ સુધી આચાર્ય દ્વારા કોઈ અહેવાલો ફોરવર્ડ કરવામાં આવ્યા નથી.',
    'fr.week_abbr': 'સપ્તાહ',
    'fr.30_day_fail': '30-દિવસ નિષ્ફળતા',
    'fr.worst': 'સૌથી ખરાબ',
    'fr.forwarded': 'ફોરવર્ડ કરેલ',
    'fr.lr_urgency': 'LR તાકીદ',
    'fr.pdf': 'પીડીએફ',
    'fr.assign': 'સોંપો',
    'fr.more_bundles': 'વધુ બંડલ · બધા જુઓ',
    'nav.logout': 'લોગ આઉટ',
    'clv.photo_on_file': 'ફાઇલમાં ફોટો',
    'clv.lr_urgency': 'LR તાકીદ',
    'clv.days_to_failure': 'નિષ્ફળતા સુધીના દિવસો',
    'clv.week': 'સપ્તાહ',
    'clv.weekly_bundle': 'સાપ્તાહિક બંડલ',
    'clv.categories': 'શ્રેણીઓ',
    'clv.category': 'શ્રેણી',
    'clv.worst': 'સૌથી ખરાબ',
    'clv.submitted': 'સબમિટ કર્યું',
    'clv.lr_urgency_score': 'LR તાકીદ સ્કોર',
    'clv.view_pdf': 'પીડીએફ જુઓ',
    'clv.sent_to_deo': 'DEO ને મોકલ્યું',
    'clv.send_to_deo': 'DEO ને મોકલો',
    'clv.assign_contractor': 'કોન્ટ્રાક્ટર સોંપો',
    'clv.lr_model_output': 'LR મોડલ આઉટપુટ (TS-PS3.csv પ્રશિક્ષિત)',
    'clv.forwarded_to_deo_on': 'ને DEO પર ફોરવર્ડ કરવામાં આવ્યું',
    'clv.loading_reports': 'રિપોર્ટ્સ લોડ થઈ રહ્યાં છે...',
    'clv.access_restricted': 'ઍક્સેસ પ્રતિબંધિત',
    'clv.auth_required': 'આ દૃશ્ય માટે આચાર્ય અથવા DEO અધિકૃતતા આવશ્યક છે.',
    'clv.account_unlinked': 'એકાઉન્ટ અનલિંક કર્યું',
    'clv.no_school': 'તમારું આચાર્ય એકાઉન્ટ શાળા સાથે સંકળાયેલું નથી.',
    'clv.deo_title': 'ફોરવર્ડ કરેલ સાપ્તાહિક અહેવાલો',
    'clv.prin_title': 'સાપ્તાહિક સ્થિતિ અહેવાલો',
    'clv.deo_subtitle': 'આચાર્યો દ્વારા ફોરવર્ડ કરાયેલ બંડલ્સ — LR તાકીદ દ્વારા ક્રમાંકિત, સૌથી વધુ તાકીદનું ટોચ પર',
    'clv.prin_subtitle': 'પ્રતિ સપ્તાહ મૂલ્યાંકન — દરેક કાર્ડ LR મોડેલ ચલાવે છે અને 3 શ્રેણીઓને બંડલ કરે છે',
    'clv.total_bundles': 'કુલ સાપ્તાહિક બંડલ્સ',
    'clv.critical_urgency': 'નિર્ણાયક તાકીદ',
    'clv.predicted_fail': 'અનુમાનિત નિષ્ફળતા < 30 દિવસ',
    'clv.sent_to_deo_stat': 'DEO ને મોકલ્યું',
    'clv.pending': 'બાકી',
    'clv.refine_view': 'દૃશ્ય રિફાઇન કરો:',
    'clv.any_urgency': 'કોઈપણ તાકીદ',
    'clv.all_bundles': 'બધા બંડલ્સ',
    'clv.awaiting_deo': 'DEO ની રાહ જોવાય છે',
    'clv.sent_filter': 'DEO ને મોકલ્યું',
    'clv.bundles_sorted': 'બંડલ · LR તાકીદ દ્વારા સૉર્ટ કરેલ',
    'clv.lr_reports': 'સાપ્તાહિક અહેવાલો (LR-અગ્રતા)',
    'clv.one_card': 'અઠવાડિયા દીઠ એક કાર્ડ — ટોચ પર સૌથી તાકીદનું',
    'clv.no_reports': 'હજુ સુધી કોઈ સાપ્તાહિક અહેવાલો સબમિટ કર્યા નથી.',
    'clv.no_match': 'કોઈ બંડલ વર્તમાન ફિલ્ટર્સ સાથે મેળ ખાતા નથી.',
    'clv.forwarding': 'ફોરવર્ડિંગ સપ્તાહ'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('appLanguage') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
    // Optionally update document lang attribute
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
